### ISSUE TITLE
Syntax error while migrating csv.

### ISSUE THREAD

**Issue by limiaspasdaniel** [graknlabs/grakn#1184]
Hello,

I'm migrating a CSV using the migration script and I think it has some kind of problems parsing doubles. Instead of building a query like "has score 9.0" it produces "has score 9,0" and then it throws a syntax error. 

This is the stacktrace:

`Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: syntax error at line 11: 
has  score 9,0,
             ^
no viable alternative at input '0'
	at ai.grakn.graql.internal.parser.QueryParser.parseQueryFragment(QueryParser.java:274)
	at ai.grakn.graql.internal.parser.QueryParser.parseQueryFragment(QueryParser.java:233)
	at ai.grakn.graql.internal.parser.QueryParser.parseQuery(QueryParser.java:118)
	at ai.grakn.graql.internal.query.QueryBuilderImpl.parse(QueryBuilderImpl.java:176)
	at ai.grakn.graql.internal.query.QueryBuilderImpl.parseTemplate(QueryBuilderImpl.java:191)
	at ai.grakn.migration.base.AbstractMigrator.template(AbstractMigrator.java:108)
	at ai.grakn.migration.csv.CSVMigrator.lambda$migrate$0(CSVMigrator.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ai.grakn.migration.base.io.MigrationCLI.writeToSout(MigrationCLI.java:107)
	at ai.grakn.migration.csv.Main.runCSV(Main.java:72)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ai.grakn.migration.csv.Main.main(Main.java:44)
	at ai.grakn.migration.base.io.MigrationCLI.die(MigrationCLI.java:185)
	at ai.grakn.migration.base.io.MigrationCLI.die(MigrationCLI.java:181)
	at ai.grakn.migration.csv.Main.runCSV(Main.java:78)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ai.grakn.migration.csv.Main.main(Main.java:44)`

I attach the template file used and the sample data, in case someone wants to try and debug. I tried by myself but I don't have the enough knowledge about the project to find out where the problem is.
[files.zip](https://github.com/graknlabs/grakn/files/801693/files.zip)

PD: I did some debugging and the syntax error is thrown at the first row of the CSV file.
PD2: The command used:

`bin/migration.sh csv -template template.gql -input idata.csv -no -k keyspace
`

**Comment by fppt** [comment]
This may be a parsing bug. @alexandraorth can you weigh in on this one?

**Comment by alexandraorth** [comment]
Hello,

This is a localisation issue, your JVM must be using another language by default. For now, you can solve this by changing the JVM options in `bin/migration.sh`. In line 19, where we call CSV migration, you should add the parameter `-Duser.language=EN` to specify English as the main language.

The whole line 19 will be:
```
java -cp ${CONCATCLASSPATH} -Duser.language=EN -Dlogback.configurationFile="${GRAKN_HOME}/conf/main/logback.xml" -Dgrakn.log.file.postprocessing="${GRAKN_HOME}/logs/grakn-postprocessing.log" -Dgrakn.log.file.main="${GRAKN_HOME}/logs/grakn.log" -Dgrakn.dir="${GRAKN_HOME}/bin" ai.grakn.migration.csv.Main ${1+"$@"}  
```

Thanks so much for bringing this up! We'll look into supporting and fixing this elsewhere in the backend. Or perhaps including that param by default. What do you think @fppt?

**Comment by alexandraorth** [comment]
#1185 This pull request proposes a potential solution to this problem.

**Comment by fppt** [comment]
The PR has been merged so I am going to close this issue. If this has not resolved your problem @limiaspasdaniel please do let us know. Thanks @alexandraorth for fixing this one.
