### ISSUE TITLE
(AbstractGraknGraph.java:1002)

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#1494]
```
Unexpected error during post processing on Job [7900f0d7-1213-4a82-8d1b-6fd6a2ce22f2] fix due to [null]
java.lang.NullPointerException: null
    at ai.grakn.graph.internal.AbstractGraknGraph.fixDuplicateResources(AbstractGraknGraph.java:1002)
    at ai.grakn.engine.postprocessing.ConceptFixer.runResourceFix(ConceptFixer.java:148)
    at ai.grakn.engine.postprocessing.ConceptFixer.lambda$checkResources$55(ConceptFixer.java:53)
    at ai.grakn.engine.postprocessing.ConceptFixer.runPostProcessingJob(ConceptFixer.java:82)
    at ai.grakn.engine.postprocessing.ConceptFixer.checkResources(ConceptFixer.java:53)
    at ai.grakn.engine.postprocessing.PostProcessing.lambda$run$18(PostProcessing.java:108)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by pouledodue** [comment]
- local macbook, OSX 10.11.6
- just testing with small onto: [onto](https://discuss.grakn.ai/t/inference-kicks-in-later/284)
- no bulk/batch loading

**Comment by pouledodue** [comment]
also this one:
```
25-04-2017 13:36:27.853 [pool-121-thread-13] ERROR post-processing - Unexpected error during post processing on Job [0406bd36-0187-4db3-bd55-649734421cd3] fix due to [ai.grakn.graph.internal.RelationImpl cannot be cast to ai.grakn.graph.internal.ResourceImpl]
java.lang.ClassCastException: ai.grakn.graph.internal.RelationImpl cannot be cast to ai.grakn.graph.internal.ResourceImpl
	at ai.grakn.graph.internal.AbstractGraknGraph.lambda$fixDuplicateResources$35(AbstractGraknGraph.java:991)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at ai.grakn.graph.internal.AbstractGraknGraph.fixDuplicateResources(AbstractGraknGraph.java:991)
	at ai.grakn.engine.postprocessing.ConceptFixer.runResourceFix(ConceptFixer.java:148)
	at ai.grakn.engine.postprocessing.ConceptFixer.lambda$checkResources$55(ConceptFixer.java:53)
	at ai.grakn.engine.postprocessing.ConceptFixer.runPostProcessingJob(ConceptFixer.java:82)
	at ai.grakn.engine.postprocessing.ConceptFixer.checkResources(ConceptFixer.java:53)
	at ai.grakn.engine.postprocessing.PostProcessing.lambda$run$18(PostProcessing.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alexandraorth** [comment]
Thanks @pouledodue. Im going to be looking into this one today.

**Comment by fppt** [comment]
Looks like @alexandraorth has resolved this one already: https://github.com/graknlabs/grakn/pull/1502 . It will be out with our next release. Thanks for brining this to our attention @pouledodue.
