### ISSUE TITLE
Failure running Java client in Windows

### ISSUE THREAD

**Issue by elymatos** [graknlabs/grakn#1913]
Hello,
I've read #1854 but I'm trying to run client (not server), the sample "example-graph-api-java-simpsons". I'm using IntelliJ, Java 1.8. Project is built, but I receive a running error:
```
-------------------- Running Simple Example --------------------
Disconnected from the target VM, address: '127.0.0.1:52086', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException
	at ai.grakn.factory.GraknSessionImpl.configureGraphFactoryRemote(GraknSessionImpl.java:151)
	at ai.grakn.factory.GraknSessionImpl.configureGraphFactory(GraknSessionImpl.java:134)
	at ai.grakn.factory.GraknSessionImpl.getConfiguredFactory(GraknSessionImpl.java:90)
	at ai.grakn.factory.GraknSessionImpl.open(GraknSessionImpl.java:79)
	at ai.grakn.example.Main.main(Main.java:86)
```
 Some clue?

The server is running at
http://ematos.net:4567/configuration?graphConfig=default

Thanks,
Ely Matos

**Comment by marco-scoppetta** [comment]
Hi @elymatos, please try re-running your project using the latest version of Grakn and feel free to open a new issues if still have problems with your use-case.
