### ISSUE TITLE
Failure running on Mac

### ISSUE THREAD

**Issue by yarax** [graknlabs/grakn#1991]
Hi!
Can't run the server
`grakn.sh start`
```
Redis is already running
Starting cassandra 
Cassandra 2.0 and later require Java 7u25 or later.
.......................... timeout exceeded (60 seconds)
Starting engine..........Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
	at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:473)
	at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:407)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1325)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:84)
	at com.thinkaurelius.titan.core.TitanFactory$Builder.open(TitanFactory.java:139)
	at ai.grakn.factory.TitanInternalFactory.configureGraph(TitanInternalFactory.java:127)
	at ai.grakn.factory.TitanInternalFactory.newTitanGraph(TitanInternalFactory.java:94)
	at ai.grakn.factory.TitanInternalFactory.buildTinkerPopGraph(TitanInternalFactory.java:90)
	at ai.grakn.factory.TitanInternalFactory.buildTinkerPopGraph(TitanInternalFactory.java:64)
	at ai.grakn.factory.AbstractInternalFactory.getTinkerPopGraph(AbstractInternalFactory.java:119)
	at ai.grakn.factory.AbstractInternalFactory.getTinkerPopGraph(AbstractInternalFactory.java:113)
	at ai.grakn.factory.AbstractInternalFactory.getGraph(AbstractInternalFactory.java:94)
	at ai.grakn.factory.AbstractInternalFactory.open(AbstractInternalFactory.java:81)
	at ai.grakn.engine.factory.EngineGraknGraphFactory.getGraph(EngineGraknGraphFactory.java:70)
	at ai.grakn.engine.SystemKeyspace.loadSystemOntology(SystemKeyspace.java:154)
	at ai.grakn.engine.SystemKeyspace.<init>(SystemKeyspace.java:82)
	at ai.grakn.engine.factory.EngineGraknGraphFactory.<init>(EngineGraknGraphFactory.java:58)
	at ai.grakn.engine.factory.EngineGraknGraphFactory.create(EngineGraknGraphFactory.java:51)
	at ai.grakn.engine.GraknEngineServer.<init>(GraknEngineServer.java:85)
	at ai.grakn.engine.GraknEngineServer.start(GraknEngineServer.java:103)
	at ai.grakn.engine.GraknEngineServer.main(GraknEngineServer.java:95)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
	... 22 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:580)
	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.<init>(AstyanaxStoreManager.java:291)
	... 27 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=127.0.0.1(127.0.0.1):9160, latency=10006(10006), attempts=1]Timed out waiting for connection
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:231)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:198)
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:84)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.executeSchemaChangeOperation(ThriftClusterImpl.java:146)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.internalCreateKeyspace(ThriftClusterImpl.java:321)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.addKeyspace(ThriftClusterImpl.java:294)
	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:575)
	... 28 more
... timeout exceeded (30 seconds)
```

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```

Grakn was installed via `brew`

Also as a wish, would be nice to have binary without .sh

**Comment by fppt** [comment]
What version of the jdk do you have?

**Comment by yarax** [comment]
```
java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by burukuru** [comment]
Are you still having issues with the Java version?
I would recommend checking what your $JAVA_HOME shell variable is pointing to the correct Java directory and removing any older version of Java you might have installed.

**Comment by CyberpunkPsychonaut** [comment]
Receiving the same error with a correctly set java home env var. OS X High Sierra

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by burukuru** [comment]
Hey @CyberpunkPsychonaut 
We've not tested the stack on Java 9 yet so I would suggest downgrading to Java 8 if you can.

**Comment by CyberpunkPsychonaut** [comment]
I have downgraded to java8u152. Everything is working fine for 30 seconds. Then I am consistently receiving a "timeout exceeded (30 seconds)" message and the server breaks.

**Comment by graphadvantage** [comment]
Same issue, using  jdk1.8.0_151

2017-10-21 15:22:12,351 [qtp1645791012-30] INFO  ai.grakn.graql.ComputeQuery - ConnectedComponentsVertexProgram is called
2017-10-21 15:22:30,048 [main] WARN  ai.grakn.engine.GraknEngineConfig - Number of threads set to 0 in properties. Running with 8 processors instead.
2017-10-21 15:22:30,051 [main] INFO  ai.grakn.engine.GraknEngineConfig - Project directory in use: /usr/local/Cellar/grakn/0.16.0/libexec/bin/
2017-10-21 15:22:30,052 [main] INFO  ai.grakn.engine.GraknEngineConfig - Configuration file in use: /usr/local/Cellar/grakn/0.16.0/libexec/conf/main/grakn.properties
2017-10-21 15:22:30,052 [main] INFO  ai.grakn.engine.GraknEngineConfig - Number of threads set to: 8
2017-10-21 15:22:30,171 [main] INFO  ai.grakn.engine.GraknEngineServer - EngineId.of(USC02RT819G8WP-7679da89-eb80-42a4-9b14-d855b1803bdb) is initializing the system ontology
2017-10-21 15:22:33,180 [main] INFO  ai.grakn.engine.GraknEngineServer - 
==================================================
2017-10-21 15:22:33,180 [main] INFO  ai.grakn.engine.GraknEngineServer - 
     ___  ___  ___  _  __ _  _     ___  ___     
    / __|| _ \/   \| |/ /| \| |   /   \|_ _|    
   | (_ ||   /| - || ' < | .` | _ | - | | |     
    \___||_|_\|_|_||_|\_\|_|\_|(_)|_|_||___|   

 Web Dashboard available at [http://0.0.0.0:4567]
2017-10-21 15:22:33,180 [main] INFO  ai.grakn.engine.GraknEngineServer - 
==================================================
2017-10-21 15:24:06,232 [qtp466075327-25] INFO  ai.grakn.graql.ComputeQuery - ConnectedComponentsVertexProgram is called
2017-10-21 15:25:21,811 [qtp466075327-25] ERROR ai.grakn.util.EngineCommunicator - Could not reach Grakn engine at [0.0.0.0:4567/initialise?graphConfig=computer&keyspace=grakn]
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at ai.grakn.util.EngineCommunicator.contactEngine(EngineCommunicator.java:79)
	at ai.grakn.util.EngineCommunicator.contactEngine(EngineCommunicator.java:106)
	at ai.grakn.factory.GraknSessionImpl.configureGraphFactoryRemote(GraknSessionImpl.java:145)
	at ai.grakn.factory.GraknSessionImpl.configureGraphFactory(GraknSessionImpl.java:130)
	at ai.grakn.factory.GraknSessionImpl.getGraphComputer(GraknSessionImpl.java:98)
	at ai.grakn.graql.internal.query.analytics.AbstractComputeQuery.getGraphComputer(AbstractComputeQuery.java:151)
	at ai.grakn.graql.internal.query.analytics.ClusterQueryImpl.execute(ClusterQueryImpl.java:82)
	at ai.grakn.engine.controller.GraqlController.formatGETAsGraql(GraqlController.java:297)
	at ai.grakn.engine.controller.GraqlController.executeGET(GraqlController.java:252)
	at ai.grakn.engine.controller.GraqlController.executeGraqlGET(GraqlController.java:153)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)

**Comment by burukuru** [comment]
Hi @graphadvantage 
Is there anything in the logs? They should be located in `/usr/local/Cellar/grakn/0.16.0/libexec/logs/`.
Can you also check if the permissions on the DB folder are correct? `/usr/local/Cellar/grakn/0.16.0/libexec/db/`

**Comment by marco-scoppetta** [comment]
Hi @yarax and @graphadvantage - we have release new versions of Grakn, please try again with latest version and let us know if you still encounter issues. Closing this.
