### ISSUE TITLE
Websocket closed, code: 1005, reason: null

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2172]
When i do
```
echo -e "clean\nconfirm" | graql.sh -k v2
```
I get

```
Exception in thread "graql-session-0" java.lang.IllegalStateException: Vertex with id 12472 was removed.
	at org.apache.tinkerpop.gremlin.structure.Element$Exceptions.elementAlreadyRemoved(Element.java:154)
	at com.thinkaurelius.titan.core.InvalidElementException.removedException(InvalidElementException.java:44)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:40)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:23)
	at com.thinkaurelius.titan.graphdb.internal.AbstractElement.isRemoved(AbstractElement.java:128)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.verifyAccess(AbstractVertex.java:71)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:120)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.properties(AbstractVertex.java:160)
	at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:70)
	at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:38)
	at ai.grakn.graph.internal.AbstractElement.property(AbstractElement.java:96)
	at ai.grakn.graph.internal.ConceptImpl.lambda$new$0(ConceptImpl.java:47)
	at ai.grakn.graph.internal.Cache.get(Cache.java:69)
	at ai.grakn.graph.internal.ConceptImpl.getId(ConceptImpl.java:142)
	at ai.grakn.graph.internal.ConceptImpl.hashCode(ConceptImpl.java:146)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at ai.grakn.graph.internal.OntologyConceptImpl.nextSubLevel(OntologyConceptImpl.java:221)
	at ai.grakn.graph.internal.OntologyConceptImpl.nextSubLevel(OntologyConceptImpl.java:225)
	at ai.grakn.graph.internal.OntologyConceptImpl.nextSubLevel(OntologyConceptImpl.java:225)
	at ai.grakn.graph.internal.OntologyConceptImpl.subs(OntologyConceptImpl.java:201)
	at ai.grakn.graph.internal.TypeImpl.subs(TypeImpl.java:242)
	at ai.grakn.engine.session.GraqlSession.getTypes(GraqlSession.java:362)
	at ai.grakn.engine.session.GraqlSession.sendTypes(GraqlSession.java:339)
	at ai.grakn.engine.session.GraqlSession.lambda$new$0(GraqlSession.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "graql-session-3" org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
	at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:299)
	at ai.grakn.engine.session.GraqlSession.lambda$sendJson$10(GraqlSession.java:350)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "graql-session-2" org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
	at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:299)
	at ai.grakn.engine.session.GraqlSession.lambda$sendJson$10(GraqlSession.java:350)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "graql-session-1" org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
	at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:299)
	at ai.grakn.engine.session.GraqlSession.lambda$sendJson$10(GraqlSession.java:350)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Websocket closed, code: 1005, reason: null
```

**Comment by pouledodue** [comment]
just a better message would help something like 'check that X is running...blablabla..`

**Comment by pouledodue** [comment]
only solution is to `grakn.sh && grakn.sh start`

**Comment by Phil-Young-Bose** [comment]
FWIW, the following work for me. I tested these commands in Grakn installed in OSX and in Docker. The command syntax I use is:

graql.sh -k grakn <<< $'clean\nconfirm\n' 

graql.sh  <<< $'clean\nconfirm\n'
