### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2175]
```
java.lang.IndexOutOfBoundsException: Index: 35, Size: 35
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at ai.grakn.graql.internal.parser.GraqlErrorListener.syntaxError(GraqlErrorListener.java:59)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:558)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportMissingToken(DefaultErrorStrategy.java:409)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenInsertion(DefaultErrorStrategy.java:512)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:476)
	at org.antlr.v4.runtime.Parser.match(Parser.java:221)
	at ai.grakn.graql.internal.antlr.GraqlParser.varPatterns(GraqlParser.java:2749)
	at ai.grakn.graql.internal.antlr.GraqlParser.insertOnly(GraqlParser.java:877)
	at ai.grakn.graql.internal.antlr.GraqlParser.insertQuery(GraqlParser.java:826)
	at ai.grakn.graql.internal.antlr.GraqlParser.query(GraqlParser.java:346)
	at ai.grakn.graql.internal.parser.QueryParser.parseQueryFragment(QueryParser.java:241)
	at ai.grakn.graql.internal.parser.QueryParser.access$100(QueryParser.java:65)
	at ai.grakn.graql.internal.parser.QueryParser$1.computeNext(QueryParser.java:166)
	at ai.grakn.graql.internal.parser.QueryParser$1.computeNext(QueryParser.java:149)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at ai.grakn.engine.session.GraqlSession.lambda$executeQuery$4(GraqlSession.java:218)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pouledodue** [comment]
happened when I was missing a semicolon at this line:  the end of this line ```$myRule has description 'this is my rule';``` in [this example](https://grakn.ai/pages/documentation/graql/graql-rules.html)

**Comment by marco-scoppetta** [comment]
Hi @pouledodue , we are investigating the issue here https://github.com/graknlabs/grakn/issues/3894.
Thank you for reporting.
