### ISSUE TITLE
Stuck on `is initializing the system ontology`

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#2220]
`0.16.0` Stuck on `Starting engine...EngineId.of(macbook-79fe34d4-678d-4017-9983-6108a098933f) is initializing the system ontology`

nothing in the logs.
`grakn.sh stop && grakn.sh start` did not help
`grakn.sh clean` did not help
reinstalling with `brew uninstall grakn && brew install grakn ` did not help

only thing that helped is rebooting the mac

**Comment by burukuru** [comment]
It's possible one of the processes was stuck in the start up or shutting down stage.
If this happens again, can you run the `grakn.sh stop` command and then `grakn.sh status` to see if there are any lingering processes.
If it still doesn't work, I can give you a hand if you hop on our [community Slack](https://grakn.ai/slack.html).

**Comment by CyberpunkPsychonaut** [comment]
Same issue. Got this after a `grakn.sh clean`

`Starting redis
Starting cassandra 
................... timeout exceeded (60 seconds)
Starting engine.EngineId.of(Cyberpunk-5546b965-6660-443f-9f42-f2cfbbf4c106) is initializing the system ontology
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager
        at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
        at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:473)
        at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:407)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1325)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:84)
        at com.thinkaurelius.titan.core.TitanFactory$Builder.open(TitanFactory.java:139)
        at ai.grakn.factory.TitanInternalFactory.configureGraph(TitanInternalFactory.java:127)
        at ai.grakn.factory.TitanInternalFactory.newTitanGraph(TitanInternalFactory.java:94)
        at ai.grakn.factory.TitanInternalFactory.buildTinkerPopGraph(TitanInternalFactory.java:90)
        at ai.grakn.factory.TitanInternalFactory.buildTinkerPopGraph(TitanInternalFactory.java:64)
        at ai.grakn.factory.AbstractInternalFactory.getTinkerPopGraph(AbstractInternalFactory.java:120)
        at ai.grakn.factory.AbstractInternalFactory.getTinkerPopGraph(AbstractInternalFactory.java:114)
        at ai.grakn.factory.AbstractInternalFactory.getGraph(AbstractInternalFactory.java:95)
        at ai.grakn.factory.AbstractInternalFactory.open(AbstractInternalFactory.java:82)
        at ai.grakn.engine.factory.EngineGraknGraphFactory.getGraph(EngineGraknGraphFactory.java:73)
        at ai.grakn.engine.SystemKeyspace.loadSystemOntology(SystemKeyspace.java:160)
        at ai.grakn.engine.GraknEngineServer.loadAndUnlock(GraknEngineServer.java:155)
        at ai.grakn.engine.GraknEngineServer.lockAndInitializeSystemOntology(GraknEngineServer.java:143)
        at ai.grakn.engine.GraknEngineServer.start(GraknEngineServer.java:127)
        at ai.grakn.engine.GraknEngineServer.main(GraknEngineServer.java:120)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
        ... 20 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Temporary failure in storage backend
        at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:580)
        at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.<init>(AstyanaxStoreManager.java:291)
        ... 25 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=127.0.0.1(127.0.0.1):9160, latency=10005(10005), attempts=1]Timed out waiting for connection
        at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:231)
        at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:198)
        at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:84)
        at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
        at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
        at com.netflix.astyanax.thrift.ThriftClusterImpl.executeSchemaChangeOperation(ThriftClusterImpl.java:146)
        at com.netflix.astyanax.thrift.ThriftClusterImpl.internalCreateKeyspace(ThriftClusterImpl.java:321)
        at com.netflix.astyanax.thrift.ThriftClusterImpl.addKeyspace(ThriftClusterImpl.java:294)
        at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:575)
        ... 26 more`

**Comment by lolski** [comment]
Can you copy and paste the output of `cassandra.log`?
