### ISSUE TITLE
EntityImpl cannot be cast to OntologyConcept

### ISSUE THREAD

**Issue by wakahiu** [graknlabs/grakn#2266]
On starting graql with `graql --keyspace refdatamasterr`, I get the 

> EntityImpl cannot be cast to OntologyConcept

Error. I've restarted grakn multiple times are killed -9 all grakn process.

Note: Graql loads correctly for other keyspaces. How can I recorver data that is in this`refdatamasterr` keyspace?

```
2017-10-24 21:09:49,366 [graql-session-0] ERROR ai.grakn.engine.session.GraqlSession - java.lang.ClassCastException: ai.grakn.graph.internal.EntityImpl cannot be cast to ai.grakn.concept.OntologyConcept
        at ai.grakn.graph.internal.OntologyConceptImpl.nextSubLevel(OntologyConceptImpl.java:224)
        at ai.grakn.graph.internal.OntologyConceptImpl.nextSubLevel(OntologyConceptImpl.java:225)
        at ai.grakn.graph.internal.OntologyConceptImpl.subs(OntologyConceptImpl.java:201)
        at ai.grakn.graph.internal.TypeImpl.subs(TypeImpl.java:242)
        at ai.grakn.graph.internal.AbstractGraknGraph.copyToCache(AbstractGraknGraph.java:301)
        at ai.grakn.graph.internal.AbstractGraknGraph.initialiseMetaConcepts(AbstractGraknGraph.java:280)
        at ai.grakn.graph.internal.AbstractGraknGraph.<init>(AbstractGraknGraph.java:132)
        at ai.grakn.graph.internal.GraknTitanGraph.<init>(GraknTitanGraph.java:54)
        at ai.grakn.factory.TitanInternalFactory.buildGraknGraphFromTinker(TitanInternalFactory.java:85)
        at ai.grakn.factory.TitanInternalFactory.buildGraknGraphFromTinker(TitanInternalFactory.java:64)
        at ai.grakn.factory.AbstractInternalFactory.getGraph(AbstractInternalFactory.java:95)
        at ai.grakn.factory.AbstractInternalFactory.open(AbstractInternalFactory.java:82)
        at ai.grakn.factory.GraknSessionImpl.open(GraknSessionImpl.java:79)
        at ai.grakn.engine.session.GraqlSession.refreshGraph(GraqlSession.java:122)
        at ai.grakn.engine.session.GraqlSession.lambda$new$0(GraqlSession.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2017-10-24 21:09:49,370 [graql-session-0] ERROR a.grakn.engine.session.RemoteSession - Websocket closed, code: 1005, reason: null

```

**Comment by fppt** [comment]
Hi @wakahiu, it seems that somehow that keyspace has become corrupted. It seems to think an Entity is a Schema Concept.

Sadly there is no simple way to fix this right now. 

Would you happen to know how you did this? This is likely a bug on our side which we should look into.
