### ISSUE TITLE
Grakn java remote connection not working

### ISSUE THREAD

**Issue by sbcd90** [graknlabs/grakn#2898]
Hello,
I'm running grakn inside a docker container following https://hub.docker.com/r/graknlabs/grakn/ , & I'm able to access the visualizer at http://localhost:4567
but, when i try to access it from java like this
```
GraknSession session = RemoteGrakn.session(Grakn.DEFAULT_URI, Keyspace.of("grakn"));

try (GraknTx tx = session.open(GraknTxType.READ)) {
}
```
it throws an exception
```
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```

Can someone plz help?

**Comment by JJSimon17** [comment]
Hi, @sbcd90 , you may try use it like this:
`GraknSession session = RemoteGrakn.session(new SimpleURI("localhost:48555"), Keyspace.of(keyspace));`

The Grakn.DEFAULT_URI actually is the frontend web address, but the session actually use grpc inside, the default port is 48555.

**Comment by marco-scoppetta** [comment]
@sbcd90 We are currently not supporting the Docker image, the one you're using it's an old version that won't work with latest APIs. Try use this version (created by @BFergerson ) https://github.com/BFergerson/grakn-docker-toolbox

**Comment by sbcd90** [comment]
@marco-scoppetta , @JJSimon17 , 
Thanks a lot. That works.
