### ISSUE TITLE
Set db directory as a docker volume cause grakn server fail to start 

### ISSUE THREAD

**Issue by gpyzy** [graknlabs/grakn#2965]
**Graknversion** - 1.3.0
**Your operating system
** - CentOS 7
**Whether it is Grakn distribution that you download, installed from brew, or Docker
** - from [Grakn GitHub release page](https://github.com/graknlabs/grakn/releases/download/v1.3.0/grakn-dist-1.3.0.tar.gz "Grakn GitHub release page")
####The steps which you did
Step 1,  I write the following dockerfile in order to build my grakn image
```
FROM openjdk:8-jdk

ARG GRAKN_VERSION=1.3.0
ENV GRAKN_HOME=/opt/grakn

RUN mkdir -p $GRAKN_HOME && \
    curl -sSL https://github.com/graknlabs/grakn/releases/download/v${GRAKN_VERSION}/grakn-dist-${GRAKN_VERSION}.tar.gz | \
    tar -C $GRAKN_HOME --strip-components=1 -xzv

ENV PATH=$PATH:$GRAKN_HOME
WORKDIR $GRAKN_HOME

COPY docker-entrypoint /usr/local/bin
RUN chmod a+x /usr/local/bin/docker-entrypoint

# Grakn Server
EXPOSE 4567
# Thrift client API
EXPOSE 9160
# Grakn gRPC
EXPOSE 48555

ENTRYPOINT [ "docker-entrypoint" ]
```
and the *docker-entrypoint* file looks like below
```bash
#!/bin/sh

grakn server start
tail -f -n +1 $GRAKN_HOME/logs/grakn.log
```
Step 2, I run the following docker cmmand to build the image and run a container
```bash
docker build -t grakn .
docker run -dt -v $(pwd)/db/:/opt/grakn/db/ -p 4567:4567 -p 9160:9160 -p 48555:48555 --name grakn grakn
```
Step 3, I check the container and found that grakn server failed to start, while I type `grakn server status` I see the following results
```
Storage: RUNNING
Queue: NOT RUNNING
Engine: NOT RUNNING
```

#### The current state of Grakn, by running these commands:
**ls -la /tmp/*.pid
**
`-rw-r--r--. 1 root root 3 Aug 18 14:41 /tmp/grakn-storage.pid
`
**ps -ef | grep redis-server
**
`root       489   476  0 15:20 pts/1    00:00:00 grep redis-server
`
**jps (if this command is installed on the system. usually is, when you are on Oracle JDK)**
```bash
113 CassandraDaemon
491 Jps
```
**The logs. If they’re quite long, maybe try only posting the last 200 lines of each**
###### - grakn.log
```bash
2018-08-18 15:12:49,332 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:12:49,335 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:12:49,366 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:12:49,366 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:15:47,497 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:15:47,500 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:15:47,529 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:15:47,529 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:15:47,530 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:15:47,530 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:15:47,852 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: /opt/grakn
2018-08-18 15:15:47,852 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: /opt/grakn/conf/grakn.properties
2018-08-18 15:15:57,921 [main] ERROR ai.grakn.engine.bootup.GraknBootup - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
ai.grakn.engine.bootup.BootupException: null
        at ai.grakn.engine.bootup.QueueBootup.start(QueueBootup.java:131)
        at ai.grakn.engine.bootup.QueueBootup.startIfNotRunning(QueueBootup.java:68)
        at ai.grakn.engine.bootup.GraknBootup.serverStart(GraknBootup.java:191)
        at ai.grakn.engine.bootup.GraknBootup.server(GraknBootup.java:143)
        at ai.grakn.engine.bootup.GraknBootup.run(GraknBootup.java:130)
        at ai.grakn.engine.bootup.GraknBootup.main(GraknBootup.java:71)

```

**Comment by lolski** [comment]
Thank you for reporting the issue. We're not at the point where we want to focus on Docker compatibility. 

However, looking at your settings, I don't see anything particularly wrong as from Grakn's perspective a Docker volume should be identical to a regular disk.

We've had an issue on CentOS where the Queue would fail to start because of a missing dependency. Therefore rather than creating your own image I would suggest you try the image maintained by our fellow user @BFergerson : https://github.com/BFergerson/grakn-docker-toolbox

**Comment by gpyzy** [comment]
Thank you @lolski. Actually my example is just based on what @BFergerson. The only modification is I use docker run -v parameter to volume grain's db folder.

**Comment by vmax** [comment]
I tried the following on the [latest `master`](https://github.com/graknlabs/grakn/commit/2091602fbcca45823d2bc3d5062ce7cdb6b25b89):

```
bazel run //:distribution-docker
docker run -v $(pwd)/db/:/server/db/ -p 48555:48555 410d787f3a3e7283d5357a149b7c86d9027b863f807021741e265e601cb13c9a
```

Then:
- loaded `basic-genealogy.gql` into `gene`
- stopped `grakn-core` container
- restarted it
- ran `match $x isa person; get;`

And it worked successfully.
