### ISSUE TITLE
Failure when testing analytics docs

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3105]
_This issue was originally posted by @haikalpribadi  on 2017-07-14 19:01_.

Somehow a query in this file returns a shard... can't reproduce locally. 
```
 ai.grakn.test.docs.GraqlDocsTest.testExamplesValidSyntax[documentation/11-examples/analytics.md] 
```
 
```
 java.lang.RuntimeException: Unknown base type [SHARD] at ai.grakn.graph.internal.ElementFactory.buildConcept(ElementFactory.java:188) at ai.grakn.graph.internal.ElementFactory.buildConcept(ElementFactory.java:139) at ai.grakn.graph.internal.AbstractGraknGraph.getConcept(AbstractGraknGraph.java:341) at ai.grakn.graph.internal.AbstractGraknGraph.getConcept(AbstractGraknGraph.java:538) at ai.grakn.graql.internal.query.match.MatchQueryBase.lambda$getAllTypeLabels$10(MatchQueryBase.java:162) at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at ai.grakn.graql.internal.query.match.MatchQueryBase.getAllTypeLabels(MatchQueryBase.java:167) at ai.grakn.graql.internal.query.match.MatchQueryBase.stream(MatchQueryBase.java:87) at ai.grakn.graql.internal.query.match.MatchQueryGraph.stream(MatchQueryGraph.java:48) at ai.grakn.graql.internal.query.match.AbstractMatchQuery.stream(AbstractMatchQuery.java:86) at ai.grakn.graql.internal.query.match.AbstractMatchQuery.execute(AbstractMatchQuery.java:74) at ai.grakn.graql.internal.query.match.AbstractMatchQuery.execute(AbstractMatchQuery.java:54) at java.util.Iterator.forEachRemaining(Iterator.java:116) at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) at ai.grakn.test.docs.GraqlDocsTest.parse(GraqlDocsTest.java:165) at ai.grakn.test.docs.GraqlDocsTest.assertGraqlStringValidSyntax(GraqlDocsTest.java:146) at ai.grakn.test.docs.GraqlDocsTest.assertGraqlCodeblockValidSyntax(GraqlDocsTest.java:140) at ai.grakn.test.docs.GraqlDocsTest.executeAssertionOnContents(GraqlDocsTest.java:126) at ai.grakn.test.docs.GraqlDocsTest.testExamplesValidSyntax(GraqlDocsTest.java:109) 
```

**Comment by kasper-piskorski** [comment]
@lolski what's the status of this?

**Comment by lolski** [comment]
This is way back when we test docs with Groovy. Let's close it @kasper-piskorski
