### ISSUE TITLE
Migrator: Improve errors when JSON is malformed

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3809]
_This issue was originally posted by @haikalpribadi  on 2017-11-28 12:19_.

Trying to migrate this malformed JSON (there is an extra comma at the end after the last property) 
```
 { "cars": [{ "car_inventory_id": 1552967089, "dealer_parent_id": 1001, "MarketScanVehicleId": 71074, ... "prev_car_usage_type": "New", "car_usage_type_change_date": null, "savings": 0, "searchKey": "Maserati_Levante_S_2017", }] } 
```
 Results in a rather mysterious 
```
 Exception in thread "main" mjson.Json$MalformedJsonException: Expected a property name, but found: null at mjson.Json$Reader.readObject(Json.java:2776) at mjson.Json$Reader.read(Json.java:2718) at mjson.Json$Reader.readArray(Json.java:2788) at mjson.Json$Reader.read(Json.java:2715) at mjson.Json$Reader.readObject(Json.java:2771) at mjson.Json$Reader.read(Json.java:2718) at mjson.Json$Reader.read(Json.java:2687) at mjson.Json$Reader.read(Json.java:2697) at mjson.Json.read(Json.java:1236) at ai.grakn.migration.json.JsonMigrator.toJsonMap(JsonMigrator.java:131) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at ai.grakn.migration.base.Migrator.print(Migrator.java:108) at ai.grakn.migration.base.MigrationCLI.loadOrPrint(MigrationCLI.java:108) at ai.grakn.migration.json.JsonMigrator.runJson(JsonMigrator.java:72) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.Collections$2.tryAdvance(Collections.java:4717) at java.util.Collections$2.forEachRemaining(Collections.java:4725) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at ai.grakn.migration.json.JsonMigrator.main(JsonMigrator.java:53) 
```

**Comment by marco-scoppetta** [comment]
Closing as we don't support Migrator anymore
