### ISSUE TITLE
Client timeouts when loading SNB SF3

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3819]
_This issue was originally posted by @haikalpribadi  on 2018-01-05 11:47_.

Reproduce with `scripts/load.sh test-snb gen SF3` Grakn is still running and ocassionaly completing batches and the REST API and Graql console are still responsive. It may be possible that something in the batch is taking a long time to execute (such as a query that accesses a super-node). The histograms give some info about the frequency of failures: 
```
 -- Histograms ------------------------------------------------------------------ ai.grakn.client.BatchExecutorClient$QueriesObservableCollapser.batch.size count = 2986 min = 1 max = 1908 mean = 375.42 stddev = 411.09 median = 281.00 75% <= 466.00 95% <= 1251.00 98% <= 1331.00 99% <= 1331.00 99.9% <= 1331.00 -- Meters ---------------------------------------------------------------------- ai.grakn.client.BatchExecutorClient$CommandQueries.attempt count = 3392 mean rate = 0.31 events/second 1-minute rate = 0.37 events/second 5-minute rate = 0.34 events/second 15-minute rate = 0.33 events/second ai.grakn.client.BatchExecutorClient.failure count = 406 mean rate = 0.04 events/second 1-minute rate = 0.04 events/second 5-minute rate = 0.06 events/second 15-minute rate = 0.05 events/second ai.grakn.migration.base.Migrator.success count = 1510709 mean rate = 137.59 events/second 1-minute rate = 137.64 events/second 5-minute rate = 99.04 events/second 15-minute rate = 117.80 events/second ai.grakn.migration.base.Migrator.total count = 2245648 mean rate = 204.52 events/second 1-minute rate = 192.34 events/second 5-minute rate = 186.74 events/second 15-minute rate = 197.65 events/second -- Timers ---------------------------------------------------------------------- ai.grakn.client.BatchExecutorClient$CommandQueries.execute count = 3392 mean rate = 0.31 calls/second 1-minute rate = 0.37 calls/second 5-minute rate = 0.34 calls/second 15-minute rate = 0.33 calls/second min = 105.95 milliseconds max = 61469.99 milliseconds mean = 22276.58 milliseconds stddev = 22092.62 milliseconds median = 16928.39 milliseconds 75% <= 38877.99 milliseconds 95% <= 60246.78 milliseconds 98% <= 60377.96 milliseconds 99% <= 60395.59 milliseconds 99.9% <= 60506.91 milliseconds 
```
 
```
 2018-01-05 09:51:05,705 [hystrix-BatchExecutor-8] DEBUG ai.grakn.client.GraknClientImpl - Sending query list size 590 to keyspace snb 2018-01-05 09:51:15,816 [hystrix-BatchExecutor-1] DEBUG ai.grakn.client.GraknClientImpl - Received 200 2018-01-05 09:51:15,820 [hystrix-BatchExecutor-1] DEBUG ai.grakn.client.GraknClientImpl - Sending query list size 117 to keyspace snb 2018-01-05 09:51:20,197 [hystrix-BatchExecutor-1] DEBUG ai.grakn.client.GraknClientImpl - Received 200 2018-01-05 09:51:20,199 [hystrix-BatchExecutor-1] DEBUG ai.grakn.client.GraknClientImpl - Sending query list size 237 to keyspace snb 2018-01-05 09:51:27,980 [hystrix-BatchExecutor-4] ERROR ai.grakn.client.BatchExecutorClient - Error while executing statement com.netflix.hystrix.exception.HystrixRuntimeException: CommandQueries failed and no fallback available. at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:819) at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804) at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472) at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at rx.observers.Subscribers$5.onError(Subscribers.java:230) at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44) at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80) at rx.observers.Subscribers$5.onError(Subscribers.java:230) at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) at rx.observers.Subscribers$5.onError(Subscribers.java:230) at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1431) at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1362) at rx.observers.Subscribers$5.onError(Subscribers.java:230) at rx.observers.Subscribers$5.onError(Subscribers.java:230) at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44) at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10256) at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.RuntimeException: Unexpected exception while retrying, 1559 queries failed. at ai.grakn.client.BatchExecutorClient$CommandQueries.run(BatchExecutorClient.java:402) at ai.grakn.client.BatchExecutorClient$CommandQueries.run(BatchExecutorClient.java:341) at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302) at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ... 26 common frames omitted Caused by: java.util.concurrent.ExecutionException: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out at com.github.rholder.retry.Retryer$ExceptionAttempt.(Retryer.java:254) at com.github.rholder.retry.Retryer.call(Retryer.java:163) at ai.grakn.client.BatchExecutorClient$CommandQueries.run(BatchExecutorClient.java:392) ... 30 common frames omitted Caused by: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155) at com.sun.jersey.api.client.Client.handle(Client.java:652) at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) at ai.grakn.client.GraknClientImpl.graqlExecute(GraknClientImpl.java:79) at ai.grakn.client.BatchExecutorClient$CommandQueries.lambda$run$1(BatchExecutorClient.java:394) at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) at com.github.rholder.retry.Retryer.call(Retryer.java:160) ... 31 common frames omitted Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) at java.net.SocketInputStream.read(SocketInputStream.java:171) at java.net.SocketInputStream.read(SocketInputStream.java:141) at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) at java.io.BufferedInputStream.read(BufferedInputStream.java:345) at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253) at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153) ... 39 common frames omitted 2018-01-05 09:51:27,981 [hystrix-BatchExecutor-4] DEBUG ai.grakn.migration.base.Migrator - Error in execution 2018-01-05 09:51:27,984 [hystrix-BatchExecutor-4] DEBUG ai.grakn.client.GraknClientImpl - Sending query list size 422 to keyspace snb 2018-01-05 09:51:33,628 [hystrix-BatchExecutor-5] DEBUG ai.grakn.client.GraknClientImpl - Received 200 2018-01-05 09:51:33,635 [hystrix-BatchExecutor-5] DEBUG ai.grakn.client.GraknClientImpl - Sending query list size 117 to keyspace snb 2018-01-05 09:51:39,960 [hystrix-BatchExecutor-1] DEBUG ai.grakn.client.GraknClientImpl - Received 200 
```

**Comment by marco-scoppetta** [comment]
Closing as we don't use SNB anymore
