### ISSUE TITLE
Core: compute path, java heap space OutOfMemoryError and RunTimeErrors afterwards

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#3902]
_This issue was originally posted by @jmsfltchr  on 2018-05-12 15:04_.

For a long compute path, which contains 32768 paths, Java crashes due to memory constraints. Query to use to replicate: 
```
compute path from V549104, to V950432, in [station, tunnel];
```
 Dataset in datasets folder on dropbox: https://www.dropbox.com/s/iq51bfyww6ro8z5/grakn-dist-1.3.0-SNAPSHOT-james-branch-bug_%2320081.zip?dl=0 The error given in Python: 
```
 File "/Users/jamesfletcher/programming/venv/lib/python3.6/site-packages/grakn/client.py", line 36, in execute raise GraknError(response.json()['exception']) grakn.client.GraknError: java.lang.OutOfMemoryError: Java heap space 
```
 The error reported in the Grakn log: 
```
 2018-05-12 13:46:26,649 [qtp1857818870-24] INFO a.g.g.i.q.r.TinkerComputeQueryExecutor - Number of path: 32768 2018-05-12 13:57:23,004 [qtp1857818870-24] WARN a.g.e.controller.GraqlController - Retrying transaction after {1} attempts due to exception {Java heap space} 2018-05-12 13:57:23,015 [qtp1857818870-24] ERROR ai.grakn.engine.HttpHandler - REST error java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space at com.github.rholder.retry.Retryer$ExceptionAttempt.(Retryer.java:254) at com.github.rholder.retry.Retryer.call(Retryer.java:163) at ai.grakn.engine.controller.GraqlController.executeFunctionWithRetrying(GraqlController.java:213) at ai.grakn.engine.controller.GraqlController.executeGraql(GraqlController.java:185) at spark.RouteImpl$1.handle(RouteImpl.java:61) at spark.http.matching.Routes.execute(Routes.java:61) at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126) at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) at org.eclipse.jetty.server.Server.handle(Server.java:517) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.OutOfMemoryError: Java heap space at java.lang.AbstractStringBuilder.(AbstractStringBuilder.java:68) at java.lang.StringBuilder.(StringBuilder.java:101) at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:394) at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83) at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3213) at ai.grakn.engine.printer.JacksonPrinter.complete(JacksonPrinter.java:52) at ai.grakn.engine.printer.JacksonPrinter.complete(JacksonPrinter.java:42) at ai.grakn.graql.GraqlConverter.convert(GraqlConverter.java:59) at ai.grakn.graql.Printer.graqlString(Printer.java:46) at ai.grakn.engine.controller.GraqlController.executeQuery(GraqlController.java:284) at ai.grakn.engine.controller.GraqlController.lambda$executeGraql$5(GraqlController.java:197) at ai.grakn.engine.controller.GraqlController$$Lambda$159/1240306432.call(Unknown Source) at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) at com.github.rholder.retry.Retryer.call(Retryer.java:160) at ai.grakn.engine.controller.GraqlController.executeFunctionWithRetrying(GraqlController.java:213) at ai.grakn.engine.controller.GraqlController.executeGraql(GraqlController.java:185) at ai.grakn.engine.controller.GraqlController$$Lambda$116/568462037.handle(Unknown Source) at spark.RouteImpl$1.handle(RouteImpl.java:61) at spark.http.matching.Routes.execute(Routes.java:61) at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126) at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) at org.eclipse.jetty.server.Server.handle(Server.java:517) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) 
```
 Following this, I stopped the server to zip a copy so that we can replicate. I restarted the server, but the engine never showed "success" starting. But, ./grakn server status reports 
```
 Storage: RUNNING Queue: RUNNING Engine: RUNNING 
```
 Running my program gave errors from Python using 
```
compute path
```
 of: 
```
 File "/Users/jamesfletcher/programming/venv/lib/python3.6/site-packages/grakn/client.py", line 36, in execute raise GraknError(response.json()['exception']) grakn.client.GraknError: None 
```
 I attempted this twice, please check the second set of log files for the errors in the Grakn log.

**Comment by flyingsilverfin** [comment]
Closed since in Grakn 2.0.0  compute has been removed, to be brought back poperly at a later date
