### ISSUE TITLE
EmbeddedGraknTx and EmbeddedGraknSession exhibits an ordering bug

### ISSUE THREAD

**Issue by grabl** [graknlabs/grakn#4183]
_This issue was originally posted by @lolski  on 2018-08-07 18:53_.

## Scenario A: Creating a transaction out of a closed session, then perform a query Steps: 1. open a session 2. close the session 3. create a transaction out of that closed session 4. perform a query using that transaction Which will execute successfully. Therefore, apparently we don't need an open session in order to perform a query. Copy and paste the following code in order to reproduce: 
```
 @Test public void openTxUsingAnAlreadyClosedSession() { EmbeddedGraknSession session = EmbeddedGraknSession.createEngineSession(Keyspace.of("grakn")); session.close(); EmbeddedGraknTx tx = session.transaction(GraknTxType.WRITE); tx.graql().match(var("x").sub("thing")).get().execute().forEach(e -> System.out.println("thing " + e.get("x"))); tx.commit(); } // executes correctly: thing Base Type [TYPE] - Id [V4344] - Label [thing] - Abstract [false] thing Base Type [ATTRIBUTE_TYPE] - Id [V4160] - Label [attribute] - Abstract [false] thing Base Type [RELATIONSHIP_TYPE] - Id [V4176] - Label [relationship] - Abstract [false] thing Base Type [ENTITY_TYPE] - Id [V4304] - Label [entity] - Abstract [false] 
```
 ## Scenario B: Creating a transaction out of an open session, then close the session before performing a query Steps: 1. open a session 2. create a transaction out of that open session 3. close the session 4. perform a query using that transaction If we reorder the operation, the fact that the session is closed suddenly becomes important and the query will fail with an exception Copy and paste the following code in order to reproduce: 
```
 @Test public void openTxUsingAnOpenSession_butExecuteQueryAfterClosingTheSession() { EmbeddedGraknSession session = EmbeddedGraknSession.createEngineSession(Keyspace.of("grakn")); EmbeddedGraknTx tx = session.transaction(GraknTxType.WRITE); session.close(); tx.graql().match(var("x").sub("thing")).get().execute().forEach(e -> System.out.println("thing " + e.get("x"))); tx.commit(); } // The session is closed! Grakn no likes!!! Let's throw! java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyOpen(StandardJanusGraphTx.java:301) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyAccess(StandardJanusGraphTx.java:289) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyWriteAccess(StandardJanusGraphTx.java:285) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:728) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:722) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addVertex(StandardJanusGraphTx.java:525) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addVertex(StandardJanusGraphTx.java:541) at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addVertex(StandardJanusGraphTx.java:537) at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:159) at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:47) at ai.grakn.kb.internal.concept.ElementFactory.addVertexElement(ElementFactory.java:294) at ai.grakn.kb.internal.EmbeddedGraknTx.addVertexElement(EmbeddedGraknTx.java:394) at ai.grakn.kb.internal.GraknTxJanus.lambda$addVertexElement$1(GraknTxJanus.java:90) at ai.grakn.kb.internal.GraknTxJanus.executeLockingMethod(GraknTxJanus.java:101) at ai.grakn.kb.internal.GraknTxJanus.addVertexElement(GraknTxJanus.java:90) at ai.grakn.kb.internal.concept.TypeImpl.addInstance(TypeImpl.java:124) at ai.grakn.kb.internal.concept.TypeImpl.putInstance(TypeImpl.java:102) at ai.grakn.kb.internal.concept.AttributeTypeImpl.putAttribute(AttributeTypeImpl.java:131) at ai.grakn.kb.internal.concept.AttributeTypeImpl.create(AttributeTypeImpl.java:116) at ai.grakn.graql.internal.query.executor.ConceptBuilder.putInstance(ConceptBuilder.java:415) at ai.grakn.graql.internal.query.executor.ConceptBuilder.tryPutConcept(ConceptBuilder.java:247) at ai.grakn.graql.internal.query.executor.ConceptBuilder.build(ConceptBuilder.java:184) at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.buildConcept(QueryOperationExecutor.java:270) at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.get(QueryOperationExecutor.java:401) at ai.grakn.graql.internal.pattern.property.HasAttributeProperty.lambda$insert$1(HasAttributeProperty.java:139) at ai.grakn.graql.internal.pattern.property.PropertyExecutor.execute(PropertyExecutor.java:76) at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:253) at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:102) at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:84) at ai.grakn.graql.internal.query.InsertQueryImpl.stream(InsertQueryImpl.java:81) at ai.grakn.engine.rpc.SessionService$TransactionListener.query(SessionService.java:243) at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:143) at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:118) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) 
```

**Comment by marco-scoppetta** [comment]
This is resolved now.
