### ISSUE TITLE
AttributeDeduplicator throws null on one test

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#4412]
```
16:15:24.086 [ForkJoinPool.commonPool-worker-7] ERROR a.g.e.a.d.AttributeDeduplicatorDaemon - An exception has occurred in the attribute de-duplicator daemon. 
java.util.NoSuchElementException: null
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicator.deduplicate(AttributeDeduplicator.java:58)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicatorDaemon.lambda$startDeduplicationDaemon$1(AttributeDeduplicatorDaemon.java:117)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by marco-scoppetta** [comment]
Removed attribute dedup!
