### ISSUE TITLE
Local behavior does not match docs on https://dev.grakn.ai/academy/insert-delete-queries.html

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4449]
On https://dev.grakn.ai/academy/insert-delete-queries.html it says "You should see a big red box warning you that you cannot run insert queries into the dashboard.", but it worked under my windows10. So I was able to insert via dashboard, might be a security problem.

At least it shows that the academy was very likely written for a different version and not tested for the actual one.

**Comment by kristall** [comment]
Also the deleting does not really work:

```
>>> match $r ($x) isa located-in; $x isa company has name "Grakn"; delete $r;
{V40964120, V40968400, V40964136, V40964304}
>>> commit
UNKNOWN: Vertex with id 40964120 was removed.. Please check server logs for the stack trace.
```

and the stack trace 

```
2018-10-10 04:12:57,897 [grpc-default-executor-1] ERROR a.g.e.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.IllegalStateException: Vertex with id 40964120 was removed.
	at org.apache.tinkerpop.gremlin.structure.Element$Exceptions.elementAlreadyRemoved(Element.java:154)
	at org.janusgraph.core.InvalidElementException.removedException(InvalidElementException.java:58)
	at org.janusgraph.graphdb.vertices.AbstractVertex.verifyAccess(AbstractVertex.java:90)
	at org.janusgraph.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:137)
	at org.janusgraph.graphdb.vertices.AbstractVertex.edges(AbstractVertex.java:173)
	at ai.grakn.kb.internal.structure.VertexElement.lambda$getEdgesOfType$0(VertexElement.java:62)
	at java.lang.Iterable.spliterator(Unknown Source)
	at ai.grakn.kb.internal.structure.VertexElement.getEdgesOfType(VertexElement.java:63)
	at ai.grakn.kb.internal.concept.RelationshipReified.castingsRelation(RelationshipReified.java:157)
	at ai.grakn.kb.internal.concept.RelationshipReified.rolePlayers(RelationshipReified.java:93)
	at ai.grakn.kb.internal.concept.RelationshipImpl.rolePlayers(RelationshipImpl.java:162)
	at ai.grakn.kb.internal.ValidateGlobalRules.validateRelationshipHasRolePlayers(ValidateGlobalRules.java:398)
	at ai.grakn.kb.internal.Validator.validateRelationship(Validator.java:144)
	at java.lang.Iterable.forEach(Unknown Source)
	at ai.grakn.kb.internal.Validator.validate(Validator.java:70)
	at ai.grakn.kb.internal.EmbeddedGraknTx.validateGraph(EmbeddedGraknTx.java:775)
	at ai.grakn.kb.internal.EmbeddedGraknTx.commitWithLogs(EmbeddedGraknTx.java:744)
	at ai.grakn.kb.internal.EmbeddedGraknTx.commitAndGetLogs(EmbeddedGraknTx.java:723)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.commit(SessionService.java:226)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:139)
	at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source
```

**Comment by kristall** [comment]
And even with the located-in relation the delete seems to work.

**Comment by sorsaffari** [comment]
@kristall Thanks for reporting these :) I've taken note of the _inserting via dashboard_ and will attend to it accordingly.
wrt the _delete_, it will be resolved as a part of a different issue ( #4447 )

**Comment by kristall** [comment]
I did test the insert with the workbase and there it actually throws an error like the academy site stated.

**Comment by marco-scoppetta** [comment]
Closing this as we don't support Academy/Dashboard anymore.
