### ISSUE TITLE
Trouble starting the engine after windows(10) restart

### ISSUE THREAD

**Issue by kristall** [graknlabs/grakn#4457]
I did a windows shutdown without stoping the grakn server. 
After starting the laptop again I checked the grakn server status with was:
```
Storage: RUNNING
Engine: NOT RUNNING 
```
so I thought I just need to start server again, but that did not work, I got the following error:
```
Storage is already running
Starting Engine.................FAILED!
Unable to start Engine.
Process exited with code '0': 'Uncaught exception at thread [Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager]
'
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '0': 'Uncaught exception at thread [Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager]
'
```
I tried to start it again (just to be sure), but the error was the same.
So I needed to stop the storage first an then start both again, then it worked.

I did not try just to start the engine. 
Maybe a "restart" option would be a good feature.

**Comment by marco-scoppetta** [comment]
It's helpful to report what's in the log files when this issues occur. 

But thank you for reporting the issue!
We will try to reproduce the same behaviour on a Windows machine.

**Comment by kristall** [comment]
@marco-scoppetta I think this is the right stuff from the log:

```
2018-10-11 00:23:21,531 [main] INFO  ai.grakn.engine.Server - 
==================================================
2018-10-11 00:23:21,531 [main] INFO  ai.grakn.engine.Server - EngineID{value=kiai-4014375c-4eaa-4370-845e-6935c51f34f2} is checking the system schema
2018-10-11 00:24:01,855 [main] ERROR ai.grakn.engine.KeyspaceStore - Error while loading system schema in 40.31 s. The error was: Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:64)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:476)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:408)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1254)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:121)
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:260)
	at ai.grakn.factory.TxFactoryJanus.configureGraph(TxFactoryJanus.java:183)
	at ai.grakn.factory.TxFactoryJanus.newJanusGraph(TxFactoryJanus.java:139)
	at ai.grakn.factory.TxFactoryJanus.buildTinkerPopGraph(TxFactoryJanus.java:135)
	at ai.grakn.factory.TxFactoryJanus.buildTinkerPopGraph(TxFactoryJanus.java:72)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.getTinkerPopGraph(TxFactoryAbstract.java:121)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.initialiseGraknTx(TxFactoryAbstract.java:115)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.openTx(TxFactoryAbstract.java:104)
	at ai.grakn.factory.TxFactoryAbstract.open(TxFactoryAbstract.java:66)
	at ai.grakn.factory.EmbeddedGraknSession.transaction(EmbeddedGraknSession.java:133)
	at ai.grakn.keyspace.KeyspaceStoreImpl.loadSystemSchema(KeyspaceStoreImpl.java:157)
	at ai.grakn.engine.Server.lockAndInitializeSystemSchema(Server.java:97)
	at ai.grakn.engine.Server.start(Server.java:70)
	at ai.grakn.engine.bootup.Grakn.main(Grakn.java:63)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 20 common frames omitted
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:608)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.<init>(AstyanaxStoreManager.java:307)
	... 25 common frames omitted
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=127.0.0.1(127.0.0.1):9160, latency=20001(20001), attempts=1]Timed out waiting for connection
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:231)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:198)
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:99)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.executeSchemaChangeOperation(ThriftClusterImpl.java:146)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.internalCreateKeyspace(ThriftClusterImpl.java:321)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.addKeyspace(ThriftClusterImpl.java:294)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:603)
	... 26 common frames omitted
2018-10-11 00:24:01,862 [main] ERROR ai.grakn.engine.bootup.Grakn - Uncaught exception at thread [Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager]
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:64)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:476)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:408)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1254)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:121)
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:260)
	at ai.grakn.factory.TxFactoryJanus.configureGraph(TxFactoryJanus.java:183)
	at ai.grakn.factory.TxFactoryJanus.newJanusGraph(TxFactoryJanus.java:139)
	at ai.grakn.factory.TxFactoryJanus.buildTinkerPopGraph(TxFactoryJanus.java:135)
	at ai.grakn.factory.TxFactoryJanus.buildTinkerPopGraph(TxFactoryJanus.java:72)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.getTinkerPopGraph(TxFactoryAbstract.java:121)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.initialiseGraknTx(TxFactoryAbstract.java:115)
	at ai.grakn.factory.TxFactoryAbstract$GraphWithTx.openTx(TxFactoryAbstract.java:104)
	at ai.grakn.factory.TxFactoryAbstract.open(TxFactoryAbstract.java:66)
	at ai.grakn.factory.EmbeddedGraknSession.transaction(EmbeddedGraknSession.java:133)
	at ai.grakn.keyspace.KeyspaceStoreImpl.loadSystemSchema(KeyspaceStoreImpl.java:157)
	at ai.grakn.engine.Server.lockAndInitializeSystemSchema(Server.java:97)
	at ai.grakn.engine.Server.start(Server.java:70)
	at ai.grakn.engine.bootup.Grakn.main(Grakn.java:63)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 20 common frames omitted
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:608)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.<init>(AstyanaxStoreManager.java:307)
	... 25 common frames omitted
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=127.0.0.1(127.0.0.1):9160, latency=20001(20001), attempts=1]Timed out waiting for connection
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:231)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:198)
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:99)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.executeSchemaChangeOperation(ThriftClusterImpl.java:146)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.internalCreateKeyspace(ThriftClusterImpl.java:321)
	at com.netflix.astyanax.thrift.ThriftClusterImpl.addKeyspace(ThriftClusterImpl.java:294)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:603)
	... 26 common frames omitted
2018-10-11 00:24:01,873 [grakn-server-shutdown] INFO  a.g.e.a.d.AttributeDeduplicatorDaemon - stopDeduplicationDaemon() - stopping the attribute de-duplicator daemon...
2018-10-11 00:24:02,361 [main] ERROR ai.grakn.engine.bootup.GraknBootup - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
ai.grakn.engine.bootup.BootupException: Process exited with code '0': 'Uncaught exception at thread [Could not instantiate implementation: org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager]
'
	at ai.grakn.engine.bootup.EngineBootup.start(EngineBootup.java:150)
	at ai.grakn.engine.bootup.EngineBootup.startIfNotRunning(EngineBootup.java:84)
	at ai.grakn.engine.bootup.GraknBootup.serverStart(GraknBootup.java:181)
	at ai.grakn.engine.bootup.GraknBootup.server(GraknBootup.java:140)
	at ai.grakn.engine.bootup.GraknBootup.run(GraknBootup.java:127)
	at ai.grakn.engine.bootup.GraknBootup.main(GraknBootup.java:69)
2018-10-11 00:24:52,964 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:52,967 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:52,969 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:52,969 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:56,307 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:56,311 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:56,312 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:56,312 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:56,313 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:56,313 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:57,482 [main] INFO  ai.grakn.engine.GraknConfig - Project directory in use: C:\Program Files\GraKn
2018-10-11 00:24:57,486 [main] INFO  ai.grakn.engine.GraknConfig - Configuration file in use: C:\Program Files\GraKn\conf\grakn.properties
2018-10-11 00:24:57,955 [main] INFO  ai.grakn.engine.Server - 
```
