### ISSUE TITLE
Bazel build depends on Python 3 which must be located precisely at /usr/bin/python3

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4495]
Bazel build depends on Python 3 which must be located precisely at `/usr/bin/python3`. The issue happens even when you're building a non-python package, such as `//server` or `//console`.

Ideally, Python should not be needed except when we're trying to build `client-python`.

For example, running this command
```
bazel build //:distribution-server //:distribution-console //:distribution-all --sandbox_debug
```

Will result in this error
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
pyenv: python3: command not found

The `python3' command exists in these Python versions:
  3.5.2

ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@python_grakn_deps//': Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/external/io_bazel_rules_python/python/pip.bzl", line 48
		_pip_import_impl(repository_ctx, "python3")
	File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/external/io_bazel_rules_python/python/pip.bzl", line 43, in _pip_import_impl
		fail(("pip_import failed: %s (%s)" % ...)))
pip_import failed:  (pyenv: python3: command not found

The `python3' command exists in these Python versions:
  3.5.2

)
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@python_grakn_deps//': Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/external/io_bazel_rules_python/python/pip.bzl", line 48
		_pip_import_impl(repository_ctx, "python3")
	File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/external/io_bazel_rules_python/python/pip.bzl", line 43, in _pip_import_impl
		fail(("pip_import failed: %s (%s)" % ...)))
pip_import failed:  (pyenv: python3: command not found

The `python3' command exists in these Python versions:
  3.5.2

)
INFO: Elapsed time: 9.792s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
Exited with code 1
```

**Comment by vmax** [comment]
@lolski can we close it as #4498 is closed?
