### ISSUE TITLE
RocksDbQueueTest::theReadMethodMustWaitUntilTheQueueBecomesNonEmpty is flaky

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#4527]
```
bazel test //server:rocks-db-queue-test
```

https://circleci.com/gh/haikalpribadi/grakn/484?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
FAIL: //server:rocks-db-queue-test (see /home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/execroot/grakn_core/bazel-out/k8-fastbuild/testlogs/server/rocks-db-queue-test/test.log)
INFO: From Testing //server:rocks-db-queue-test:
==================== Test output for //server:rocks-db-queue-test:
JUnit4 Test Runner
.E...
Time: 1.21
There was 1 failure:
1) theReadMethodMustWaitUntilTheQueueBecomesNonEmpty(ai.grakn.core.server.attribute.deduplicator.RocksDbQueueTest)
java.lang.AssertionError: 
Expected: <[added-after-300ms, added-after-read]>
     but: was <[added-after-read, added-after-300ms]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at ai.grakn.core.server.attribute.deduplicator.RocksDbQueueTest.theReadMethodMustWaitUntilTheQueueBecomesNonEmpty(RocksDbQueueTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

```

**Comment by lolski** [comment]
Can be reliable reproduced on CircleCI with
```
bazel test //server:rocks-db-queue-test --test_filter=grakn.core.server.deduplicator.RocksDbQueueTest#theReadMethodMustWaitUntilTheQueueBecomesNonEmpty --test_output=errors --cache_test_results=no --runs_per_test=120
```
