### ISSUE TITLE
client-java fails at runtime with 'AbstractMethodError ' exception, which only happens when ran from IntelliJ, possibly due to an ordering issue in loading the JARs during runtime

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#4553]
The following exception commonly happens when running the [grakn-java-client-example](https://github.com/lolski/grakn-java-client-example) which uses `client-java`:

```
Exception in thread "main" java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/ThreadFactory;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:198)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:182)
	at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:104)
	at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:74)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:503)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:337)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:405)
	at ai.grakn.client.Grakn.<init>(Grakn.java:113)
	at ai.grakn.client.Grakn.<init>(Grakn.java:91)
	at com.lolski.Main.main(Main.java:22)
```

*However*, running the same program from the command line works fine:
```
$ mvn package
$ cd target
$ tar -xf grakn-java-client-example-1.0-SNAPSHOT.tar.gz
$ cd grakn-java-client-example-1.0-SNAPSHOT
$ ./grakn-java-client-example

defining the parent-child schema...
inserting parent...
inserting child...
creating parent-child relationship...
print the created relationship, and perform aggregate count followed by compute count queries...
V12368 name = Johnny Sr. (prnt) --> (chld) V16592 Johnny Jr. via relationship 'RemoteRelationship{tx=ai.grakn.remote.RemoteGraknTx@1c7696c6, getId=V16536}
performing count using match - aggregate count...person instance count = 2, name instance count = 2
performing count using compute count...person instance count = 2, name instance count = 2
```

The issue most probably is caused due to an ordering issue where IntellIJ happens to load the JARs in a bad order. Ideally, the JARs should be able to be loaded in *any order*. There shouldn't be an order which causes an issue.

We investigated netty which sounds likely to be the culprit.

Running `mvn dependency:tree -Dincludes=io.netty -Dverbose` shows that there are many netty related artifacts included as transitive dependencies, which are likely to clash
```
[INFO] com.lolskillz:grakn-java-client-example:jar:1.0-SNAPSHOT
[INFO] \- ai.grakn:client-java:jar:1.5.0-SNAPSHOT:compile
[INFO]    +- ai.grakn:grakn-graql:jar:1.5.0-SNAPSHOT:compile
[INFO]    |  +- com.datastax.cassandra:cassandra-driver-core:jar:3.5.1:compile
[INFO]    |  |  \- io.netty:netty-handler:jar:4.0.56.Final:compile
[INFO]    |  |     +- io.netty:netty-buffer:jar:4.0.56.Final:compile
[INFO]    |  |     +- (io.netty:netty-transport:jar:4.0.56.Final:compile - omitted for conflict with 4.1.27.Final)
[INFO]    |  |     \- io.netty:netty-codec:jar:4.0.56.Final:compile
[INFO]    |  |        \- (io.netty:netty-transport:jar:4.0.56.Final:compile - omitted for duplicate)
[INFO]    |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.14.Final:compile
[INFO]    |  +- org.apache.cassandra:cassandra-all:jar:3.11.3:compile
[INFO]    |  |  \- (io.netty:netty-all:jar:4.0.44.Final:compile - omitted for conflict with 4.1.30.Final)
[INFO]    |  +- org.apache.hadoop:hadoop-common:jar:2.7.2:compile
[INFO]    |  |  \- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO]    |  |     \- (io.netty:netty:jar:3.7.0.Final:compile - omitted for conflict with 3.6.2.Final)
[INFO]    |  +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.2:compile
[INFO]    |  |  \- io.netty:netty:jar:3.6.2.Final:compile
[INFO]    |  +- org.apache.spark:spark-core_2.11:jar:2.2.0:compile
[INFO]    |  |  +- org.apache.hadoop:hadoop-client:jar:2.6.5:compile
[INFO]    |  |  |  \- org.apache.hadoop:hadoop-hdfs:jar:2.6.5:compile
[INFO]    |  |  |     \- (io.netty:netty:jar:3.6.2.Final:compile - omitted for duplicate)
[INFO]    |  |  +- org.apache.spark:spark-network-common_2.11:jar:2.2.0:compile
[INFO]    |  |  |  \- (io.netty:netty-all:jar:4.0.43.Final:compile - omitted for conflict with 4.0.44.Final)
[INFO]    |  |  +- (io.netty:netty-all:jar:4.0.43.Final:compile - omitted for conflict with 4.0.44.Final)
[INFO]    |  |  \- (io.netty:netty:jar:3.9.9.Final:compile - omitted for conflict with 3.6.2.Final)
[INFO]    |  \- org.apache.tinkerpop:spark-gremlin:jar:3.3.3:compile
[INFO]    |     +- (io.netty:netty-all:jar:4.0.43.Final:compile - omitted for conflict with 4.0.44.Final)
[INFO]    |     \- (io.netty:netty:jar:3.9.9.Final:compile - omitted for conflict with 3.6.2.Final)
[INFO]    +- io.grpc:grpc-netty:jar:1.15.0:compile
[INFO]    |  +- io.netty:netty-codec-http2:jar:4.1.27.Final:compile
[INFO]    |  |  +- io.netty:netty-codec-http:jar:4.1.27.Final:compile
[INFO]    |  |  |  \- (io.netty:netty-codec:jar:4.1.27.Final:compile - omitted for conflict with 4.0.56.Final)
[INFO]    |  |  \- (io.netty:netty-handler:jar:4.1.27.Final:compile - omitted for conflict with 4.0.56.Final)
[INFO]    |  \- io.netty:netty-handler-proxy:jar:4.1.27.Final:compile
[INFO]    |     +- io.netty:netty-transport:jar:4.1.27.Final:compile
[INFO]    |     |  +- (io.netty:netty-buffer:jar:4.1.27.Final:compile - omitted for conflict with 4.0.56.Final)
[INFO]    |     |  \- io.netty:netty-resolver:jar:4.1.27.Final:compile
[INFO]    |     +- io.netty:netty-codec-socks:jar:4.1.27.Final:compile
[INFO]    |     |  \- (io.netty:netty-codec:jar:4.1.27.Final:compile - omitted for conflict with 4.0.56.Final)
[INFO]    |     \- (io.netty:netty-codec-http:jar:4.1.27.Final:compile - omitted for duplicate)
[INFO]    \- io.netty:netty-all:jar:4.1.30.Final:compile
```

Excluding `netty-handler` seems to fix the issue:
```
            <groupId>ai.grakn</groupId>
            <artifactId>client-java</artifactId>
            <version>1.5.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-handler</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

However, we need to perform more investigation to fully understand the problem and fix it properly.

**Comment by marco-scoppetta** [comment]
This has been fixed when moving to Bazel
