### ISSUE TITLE
Grakn exception loop

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#4830]
Hello,

Since we changed our Grakn schema and load new data, despite many Grakn server restarts, multiple exceptions occured on the attribute de-deduplicator daemon, showing this error:

> 2019-01-20 15:10:21,498 [ForkJoinPool.commonPool-worker-1] ERROR a.g.e.a.d.AttributeDeduplicatorDaemonImpl - An exception has occurred in the attribute de-duplicator daemon. 
java.util.NoSuchElementException: null
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicator.deduplicate(AttributeDeduplicator.java:55)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicatorDaemonImpl.lambda$startDeduplicationDaemon$1(AttributeDeduplicatorDaemonImpl.java:121)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

> 2019-01-20 15:10:22,578 [ForkJoinPool.commonPool-worker-1] ERROR a.g.e.a.d.AttributeDeduplicatorDaemonImpl - An exception has occurred in the attribute de-duplicator daemon. 
java.util.NoSuchElementException: null
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicator.deduplicate(AttributeDeduplicator.java:55)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicatorDaemonImpl.lambda$startDeduplicationDaemon$1(AttributeDeduplicatorDaemonImpl.java:121)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

> 2019-01-20 15:10:23,622 [ForkJoinPool.commonPool-worker-1] ERROR a.g.e.a.d.AttributeDeduplicatorDaemonImpl - An exception has occurred in the attribute de-duplicator daemon. 
java.util.NoSuchElementException: null
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicator.deduplicate(AttributeDeduplicator.java:55)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicatorDaemonImpl.lambda$startDeduplicationDaemon$1(AttributeDeduplicatorDaemonImpl.java:121)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

> 2019-01-20 15:10:24,667 [ForkJoinPool.commonPool-worker-1] ERROR a.g.e.a.d.AttributeDeduplicatorDaemonImpl - An exception has occurred in the attribute de-duplicator daemon. 
java.util.NoSuchElementException: null
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicator.deduplicate(AttributeDeduplicator.java:55)
	at ai.grakn.engine.attribute.deduplicator.AttributeDeduplicatorDaemonImpl.lambda$startDeduplicationDaemon$1(AttributeDeduplicatorDaemonImpl.java:121)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

This message is always display, multiple times by second.

Best regards,
Samuel

**Comment by lolski** [comment]
Hi! Are you able to specify the steps which allow us to reproduce the issue on our end?

**Comment by SamuelHassine** [comment]
Hello,

I can not specify the steps to reproduce the issue, but we clean up Grakn multiple times and the issue is still occurring. Maybe we can provide you in private our schema and the script we are using to load data.

Best regards,
Samuel

**Comment by lolski** [comment]
Yes, that would be be helpful. Please send it to ganeshwara at grakn.ai.

**Comment by marco-scoppetta** [comment]
@SamuelHassine thank you for reporting the issue, we found what was causing the AttributeDeduplicator to print all those null pointer exceptions and we have fixed it in this PR https://github.com/graknlabs/grakn/pull/5020

Grakn 1.5 will contain this fix.
