### ISSUE TITLE
Concurrent queries on REST API fire exceptions

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#4864]
Hello,

During our tests,  a simple "match" query repeated multiple times leads to the following exception.

**The exception only fire when queries are made with infer=true on the REST API:**

`2019-02-05 01:00:33,109 [qtp1144693653-823] WARN  a.g.e.controller.GraqlController - Retrying transaction after {1} attempts due to exception {null}
2019-02-05 01:00:33,110 [qtp1144693653-823] ERROR ai.grakn.engine.ServerHTTP - REST error
java.util.ConcurrentModificationException: null
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ai.grakn.graql.internal.reasoner.atom.Atom.getApplicableRules(Atom.java:204)
	at ai.grakn.graql.internal.reasoner.atom.Atom.isRuleResolvable(Atom.java:85)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at ai.grakn.graql.internal.reasoner.query.ReasonerQueryImpl.isRuleResolvable(ReasonerQueryImpl.java:235)
	at ai.grakn.graql.internal.query.match.MatchInfer.stream(MatchInfer.java:69)
	at ai.grakn.graql.internal.query.match.MatchTx.stream(MatchTx.java:51)
	at ai.grakn.graql.internal.query.match.MatchOffset.stream(MatchOffset.java:47)
	at ai.grakn.graql.internal.query.match.MatchLimit.stream(MatchLimit.java:47)
	at ai.grakn.graql.internal.query.match.AbstractMatch.stream(AbstractMatch.java:69)
	at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:72)
	at ai.grakn.graql.internal.query.GetQueryImpl.stream(GetQueryImpl.java:65)
	at ai.grakn.graql.Query.execute(Query.java:60)
	at ai.grakn.engine.controller.GraqlController.executeAndMonitor(GraqlController.java:298)
	at ai.grakn.engine.controller.GraqlController.executeQuery(GraqlController.java:280)
	at ai.grakn.engine.controller.GraqlController.lambda$executeGraql$5(GraqlController.java:193)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at ai.grakn.engine.controller.GraqlController.executeFunctionWithRetrying(GraqlController.java:209)
	at ai.grakn.engine.controller.GraqlController.executeGraql(GraqlController.java:182)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
`

I already know that this is my 4th issue without data or repro case but we are facing a lot of issues using Grakn as our knowledge database backend. I just drop it here and we will open the code and the schema in a few days.

Best regards,
Samuel

**Comment by marco-scoppetta** [comment]
@SamuelHassine, thanks for reporting the issue,

we are not maintain the HTTP endpoints anymore in favour of HTTP2 gRPC clients (Java, Node and Python are available). 
In general my suggestion would be to try and switch to one of the clients, given that we will remove REST endpoints in Grakn 1.5.

Please let us know how it goes and what are your other issues. Better to use the discussion forum or Slack.

Thank you
