### ISSUE TITLE
executing an undefine query on a write transaction (followed by closing the transaction), should not commit the changes

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/grakn#4880]
Grakn version: 1.5 SNAPSHOT

```
package test.generated;

import grakn.core.client.GraknClient;
import grakn.core.rule.GraknTestServer;
import grakn.core.server.Transaction;
import org.junit.*;
import grakn.core.graql.query.*;

public class GraqlSnippetTest {
    @ClassRule
    public static final GraknTestServer server = new GraknTestServer();

    @Test
    public void test() {
        GraknClient client = new GraknClient(server.grpcUri().toString());
        GraknClient.Session session = client.session("test_keyspace");

        // define nickname and commit
        GraknClient.Transaction initialTransaction = session.transaction(Transaction.Type.WRITE);
        String defineQuery = "define nickname sub attribute, datatype string;";
        initialTransaction.execute((DefineQuery) Graql.parse(defineQuery));
        initialTransaction.commit();

        // undefine nickname without committing
        GraknClient.Transaction writeTransaction = session.transaction(Transaction.Type.WRITE);
        String undefineQuery = "undefine nickname sub attribute;";
        writeTransaction.execute((UndefineQuery) Graql.parse(undefineQuery));
        writeTransaction.close();

        // get nickname instances
        GraknClient.Transaction readTransaction = session.transaction(Transaction.Type.READ);
        String getQuery = "match $x isa nickname; get;";
        readTransaction.execute((GetQuery) Graql.parse(getQuery));
        readTransaction.close();

        session.close();
    }
}
```

## Expected outcome:
test to pass.

## Actual outcome
throws:
```
1) test(test.generated.GraqlSnippetTest)
grakn.core.client.exception.GraknClientException: INVALID_ARGUMENT: GraqlQueryException-label 'nickname' not found. Please check server logs for the stack trace.
	at grakn.core.client.exception.GraknClientException.create(GraknClientException.java:41)
	at grakn.core.client.GraknClient$Transaction.responseOrThrow(GraknClient.java:273)
	at grakn.core.client.GraknClient$Transaction.rpcIterator(GraknClient.java:237)
	at grakn.core.client.GraknClient$Transaction.lambda$stream$4(GraknClient.java:227)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at grakn.core.client.GraknClient$Transaction.stream(GraknClient.java:228)
	at grakn.core.server.Transaction.execute(Transaction.java:156)
	at grakn.core.server.Transaction.execute(Transaction.java:152)
	at test.generated.GraqlSnippetTest.test(GraqlSnippetTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by flyingsilverfin** [comment]
Confirmed not to be an issue as of Grank 1.5.9
