### ISSUE TITLE
Committing delete query throws UNKNOWN

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#5084]
Appears to be the same issue as #4447.

### To reproduce:
```
Start Grakn 1.5

git clone -b delete-test-1.5 https://github.com/BFergerson/grakn-calendar-test
cd grakn-calendar-test && ./gradlew run
```

### Result:
```
Ontology setup

Most recent thing inserted: [[$d/V45088][$m/V32904][$t/V28808]]
Most recent thing inserted: [[$d/V45088][$m/V37000][$t/V57544]]
Inserted things
Exception in thread "main" grakn.client.exception.GraknClientException: UNKNOWN: Vertex with id 32904 was removed.. Please check server logs for the stack trace.
        at grakn.client.exception.GraknClientException.create(GraknClientException.java:36)
        at grakn.client.GraknClient$Transaction.responseOrThrow(GraknClient.java:297)
        at grakn.client.GraknClient$Transaction.commit(GraknClient.java:307)
        at grakn.core.api.Transaction$commit$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at GraknCalendarTest.main(GraknCalendarTest.groovy:41)
```

**Comment by flyingsilverfin** [comment]
I'm looking into this again! One thing I noticed is that the problem goes away if you use a new transaction each iteration. Will investigate why it breaks within a single transaction now :)

**Comment by flyingsilverfin** [comment]
Brandon, I've found the issue and it stems from a technical debt we've known about for a while, but it's not likely to be fixed in the very near term - the current workaround that should work in most cases is to use a new transaction between inserting and deleting a relation :)
