### ISSUE TITLE
Concurrency exception when write and read at the same time

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#5118]
## Description

When a WRITE transaction is opened on a vertex in a session and, at the same time, a READ transaction is opened on the same vertex and in the same session before the WRITE transaction has been committed, an exception occurred.

## Environment

1. Ubuntu 16.04
2. Grakn Core 1.5.1
3. client-nodejs

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a session
2. Open a WRITE transaction on a vertex
3. Do some operations
4. Open a READ transaction on the same vertex
5. Query the vertex

## Expected Output

No exception.

## Actual Output

An exception occurred:

`2019-04-18 01:04:07,168 [grpc-default-executor-1088] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: Provided ConceptId is NULL
	at grakn.core.concept.ConceptId.<init>(ConceptId.java:46)
	at grakn.core.concept.ConceptId.of(ConceptId.java:57)
	at grakn.core.server.kb.concept.ElementFactory.buildConcept(ElementFactory.java:149)
	at grakn.core.server.kb.concept.ElementFactory.buildConcept(ElementFactory.java:144)
	at grakn.core.server.session.TransactionOLTP.buildConcept(TransactionOLTP.java:376)
	at grakn.core.server.kb.concept.ThingImpl.lambda$getShortcutNeighbours$15(ThingImpl.java:251)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at grakn.core.server.rpc.SessionService$Iterators.next(SessionService.java:434)
	at grakn.core.server.rpc.SessionService$TransactionListener.next(SessionService.java:398)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:200)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

## Additional information

None.

**Comment by flyingsilverfin** [comment]
@SamuelHassine thanks for the report, we've been trying to nail down the NULL concept ID for a while! Would you mind clarifying a couple points:
* Are these transactions opened in different threads on the client side?
* What exactly do you mean by "opening transaction on a vertex"? Transactions aren't bound to anything other than the keyspace
* Is the vertex being created in the the first write transaction? Or is was it a pre-existing one and you're querying for it?
* The "Some operations" are write operations on that specific vertex, not read operations?

Thank you!

**Comment by SamuelHassine** [comment]
Hello,

Here are the answers:

- _Are these transactions opened in different threads on the client side?_
  - No, it is a GraphQL API requested by multiple clients at the same time but running in a single thread, in an asynchronous wait.
- _What exactly do you mean by "opening transaction on a vertex"? Transactions aren't bound to anything other than the keyspace_
  - Sorry for the confusion, just open 2 transactions:
    - One in WRITE, and do multiple operations just to take a few seconds (ie. select an attribute to get its type, delete an attribute, create an attribute)
    - At the same time, one in READ, just with a query like `match $x id VXXXX` and concept.attributes() for instance.
- _Is the vertex being created in the the first write transaction? Or is was it a pre-existing one and you're querying for it?_
  - The vertex already exists, the WRITE transaction is for updating attributes, the READ transaction just to get it.
- _The "Some operations" are write operations on that specific vertex, not read operations?_
  - On the WRITE transaction, we mix read and write operation, for instance to get the attribute type, delete the attribute and insert an attribute with a correct syntax.
