### ISSUE TITLE
Broken vertex after multiple attempts of READ/WRITE transactions from different sessions

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#5119]
## Description

When multiple sessions are opened from different processes and these processes try to open WRITE or READ transactions on the same VERTEX, the following exceptions are fired and seem to be legitimate:

`2019-04-18 01:12:40,996 [grpc-default-executor-1094] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.server.exception.TemporaryWriteException: Internal locking exception. Please clear the transaction and try again.
	at grakn.core.server.exception.TemporaryWriteException.temporaryLock(TemporaryWriteException.java:47)
	at grakn.core.server.session.TransactionOLTP.executeLockingMethod(TransactionOLTP.java:226)
	at grakn.core.server.session.TransactionOLTP.commitTransactionInternal(TransactionOLTP.java:182)
	at grakn.core.server.session.TransactionOLTP.commitWithLogs(TransactionOLTP.java:899)
	at grakn.core.server.session.TransactionOLTP.commitAndGetLogs(TransactionOLTP.java:856)
	at grakn.core.server.rpc.SessionService$TransactionListener.commit(SessionService.java:296)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:194)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1390)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit(JanusGraphBlueprintsGraph.java:298)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
	at grakn.core.server.session.TransactionOLTP.lambda$commitTransactionInternal$1(TransactionOLTP.java:188)
	at grakn.core.server.session.TransactionOLTP.executeLockingMethod(TransactionOLTP.java:223)
	... 11 common frames omitted
Caused by: org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:56)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:91)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:139)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:196)
	at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:134)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:733)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1379)
	... 15 common frames omitted
Caused by: org.janusgraph.diskstorage.locking.PermanentLockingException: Expected value mismatch for KeyColumn [k=0x192-  0-  0-  0-  0-  0-162-  0, c=0x 36]: expected=[ 40-141- 84- 32-152-255] vs actual=[] (store=edgestore)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkSingleExpectedValueUnsafe(ExpectedValueCheckingTransaction.java:276)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.access$000(ExpectedValueCheckingTransaction.java:48)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction$1.call(ExpectedValueCheckingTransaction.java:219)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction$1.call(ExpectedValueCheckingTransaction.java:216)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkSingleExpectedValue(ExpectedValueCheckingTransaction.java:216)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkAllExpectedValues(ExpectedValueCheckingTransaction.java:190)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.prepareForMutations(ExpectedValueCheckingTransaction.java:155)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:72)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:94)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:91)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
	... 21 common frames omitted
`
But after dozens of very close attempts, **the vertex seems to be definitly broken, even after restarting Grakn Core**.

## Environment

1. Ubuntu 16.04
2. Grakn Core 1.5.1
3. client-nodejs

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open multiple sessions
2. Open multiple WRITE transactions from the sessions on the same vertex
3. Do some operations even if it fails
4. Try to READ the vertex

## Expected Output

Vertex should be readable.

## Actual Output

An exception occurred and the vertex is definitly not readable:

`2019-04-18 01:16:04,788 [grpc-default-executor-4] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: Provided ConceptId is NULL
	at grakn.core.concept.ConceptId.<init>(ConceptId.java:46)
	at grakn.core.concept.ConceptId.of(ConceptId.java:57)
	at grakn.core.server.kb.concept.ElementFactory.buildConcept(ElementFactory.java:149)
	at grakn.core.server.kb.concept.ElementFactory.buildConcept(ElementFactory.java:144)
	at grakn.core.server.session.TransactionOLTP.buildConcept(TransactionOLTP.java:376)
	at grakn.core.server.kb.concept.ThingImpl.lambda$getShortcutNeighbours$15(ThingImpl.java:251)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at grakn.core.server.rpc.SessionService$Iterators.next(SessionService.java:434)
	at grakn.core.server.rpc.SessionService$TransactionListener.next(SessionService.java:398)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:200)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
 
## Additional information

None.

**Comment by marco-scoppetta** [comment]
Samuel please report new issue if this still occurs with latest Grakn, closing for now as we have not managed to reproduce this using the last two versions of Grakn
