### ISSUE TITLE
Deleting entity and its relations trigger exception since 1.5.1

### ISSUE THREAD

**Issue by SamuelHassine** [graknlabs/grakn#5125]
## Description

Before the 1.5.1 version, we do not encounter any problem running this query:

`match $x id ${id}; $z($x, $y); delete $z, $x;`

Since the 1.5.1, this query fails if $z can be an inferred relation. 

## Environment

1. Ubuntu 18.04
2. Grakn Core 1.5.1
3. client-nodejs

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Insert a rule to infer relations between 2 entities based on a 3rd entity
2. Create 3 entities and a relation between 2 of them, to infer a relation with the 3rd entity
3. Execute the query `match $x id ${id}; $z($x, $y); delete $z, $x;` on an entity (with actual relation) with default infer at true

## Expected Output

Deletion.

## Actual Output

Exception: 

`2019-04-18 20:11:57,524 [grpc-default-executor-410] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.server.exception.TransactionException: Cannot build a concept from element {v[1302648]} due to it being deleted.
	at grakn.core.server.exception.TransactionException.create(TransactionException.java:73)
	at grakn.core.server.exception.TransactionException.invalidElement(TransactionException.java:315)
	at grakn.core.server.kb.concept.ElementFactory.buildVertexElement(ElementFactory.java:277)
	at grakn.core.server.kb.structure.EdgeElement.source(EdgeElement.java:58)
	at grakn.core.server.kb.structure.Casting.lambda$new$2(Casting.java:50)
	at grakn.core.server.kb.cache.Cache.get(Cache.java:91)
	at grakn.core.server.kb.structure.Casting.getRelation(Casting.java:106)
	at grakn.core.server.kb.concept.ThingImpl.lambda$delete$5(ThingImpl.java:119)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at grakn.core.server.kb.concept.ThingImpl.delete(ThingImpl.java:123)
	at grakn.core.graql.executor.QueryExecutor.lambda$delete$15(QueryExecutor.java:322)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at grakn.core.graql.executor.QueryExecutor.delete(QueryExecutor.java:314)
	at grakn.core.server.session.TransactionOLTP.stream(TransactionOLTP.java:264)
	at grakn.core.api.Transaction.stream(Transaction.java:299)
	at grakn.core.server.rpc.SessionService$TransactionListener.query(SessionService.java:317)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:197)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
 
## Additional information

With `wTx.query(query, { infer: false });`, the query is executed and the entity is successfully deleted.

**Comment by flyingsilverfin** [comment]
Hi -

we've tried to reproduce the bug with the following code on `1.5.1`:

schema and data:
```
define

baseEntity sub entity, plays from, plays to;
someRelation sub relation, relates from, relates to;
inferredRelation sub relation, relates from, relates to;


someRule sub rule,
when {
    (from: $x, to: $y) isa someRelation;
    (from: $z, to: $y) isa someRelation;
},
then {
    (from: $x, to: $z) isa inferredRelation;
};
insert

#Instances

$a isa baseEntity;
$b isa baseEntity;
$c isa baseEntity;


(from: $a, to: $b) isa someRelation;
(from: $c, to: $b) isa someRelation;
```

and then using one of the  ID's that plays `from` in `someRelation`:
```
match $x id {ID}; $z ($x, $y); delete $x, $z;
```
however we don't get any errors. 

Can you advise on how your schema and operations are different? Preferably with a code excerpt :)

Thank you!

**Comment by marco-scoppetta** [comment]
Closing as we were not able to replicate it.
If happens again, please create issue with reproducible steps
