### ISSUE TITLE
A Client located on a local machine is unable to connect to Grakn running on GCP

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/grakn#5276]
## Description

When Grakn Core is running on a google cloud instance and a client located on a local machine tries to connect to it - it fails.

### Scenario 1: Changed server host in Grakn.properties to external ip and connect using external ip

```server.host={external ip}```

```sudo /opt/biograkn/grakn console -r {external ip}:48555 -k test_keyspace```

**Error:**
```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at grakn.core.protocol.SessionServiceGrpc$SessionServiceBlockingStub.open(SessionServiceGrpc.java:273)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:170)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:138)
	at grakn.client.GraknClient.session(GraknClient.java:125)
	at grakn.core.console.ConsoleSession.<init>(ConsoleSession.java:90)
	at grakn.core.console.GraknConsole.run(GraknConsole.java:110)
	at grakn.core.console.GraknConsole.main(GraknConsole.java:141)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /104.198.24.162:48555
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Scenario 2: Changed server host in Grakn.properties to 0.0.0.0 and connect using internal ip
```server.host=0.0.0.0```
```telnet {internal ip} 48555```

**Error:**
telnet unable to connect

## Environment

1. OS (where Grakn server runs): Linux - Google Cloud
2. Grakn version (and platform): 1.5.5
3. Grakn client: all

## Reproducible Steps

1. Spawn instance of google cloud machine
2. Run Grakn Core on it
3. Connect to Grakn from local machine

## Expected Output
Connection successful

## Actual Output
Connection fails

**Comment by Irtazaraza** [comment]
Issue is invalid due to firewall-rule being absent
