### ISSUE TITLE
prettier message for ` Connection refused`

### ISSUE THREAD

**Issue by pouledodue** [graknlabs/grakn#5314]
when server is not running, Grakn could possibly  print a cleaner message than this:
```
$ grakn console
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at grakn.protocol.session.SessionServiceGrpc$SessionServiceBlockingStub.open(SessionServiceGrpc.java:273)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:165)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:136)
	at grakn.client.GraknClient.session(GraknClient.java:123)
	at grakn.core.console.ConsoleSession.<init>(ConsoleSession.java:90)
	at grakn.core.console.GraknConsole.run(GraknConsole.java:109)
	at grakn.core.console.GraknConsole.main(GraknConsole.java:140)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/fe80:0:0:0:0:0:0:1%1:48555
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
```

**Comment by flyingsilverfin** [comment]
Completed with #5399
