### ISSUE TITLE
Keyspace naming restricted due to CQL Cassandra driver

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/grakn#5356]
## Description
As of #5326 , we have new restrictions on what keyspaces can be named. It appears the keyspace name is passed directly to CQL which interprets it as a keyword. The bug may need to be fixed in CQL/Janus.

At the very least we should offer a better error message than the current 
```
io.grpc.StatusRuntimeException: UNKNOWN: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager. Please check server logs for the stack trace.
```

The list of restricted CQL keywords is at http://cassandra.apache.org/doc/latest/cql/appendices.html

## Environment
Grakn Core 1.5.8 (as of #5326)

## Reproducible Steps
Run:
```
./grakn console -k schema
```

## Expected Output
Open a keyspace with name `schema`

## Actual Output
From benchmark:
```
io.grpc.StatusRuntimeException: UNKNOWN: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager. Please check server logs for the stack trace.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at grakn.protocol.session.SessionServiceGrpc$SessionServiceBlockingStub.open(SessionServiceGrpc.java:273)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:165)
	at grakn.client.GraknClient$Session.<init>(GraknClient.java:136)
	at grakn.client.GraknClient.session(GraknClient.java:123)
	at grakn.benchmark.profiler.util.SchemaManager.loadSchema(SchemaManager.java:43)
	at grakn.benchmark.profiler.usecase.LoadSchema.run(LoadSchema.java:24)
	at grakn.benchmark.profiler.GraknBenchmark.start(GraknBenchmark.java:83)
	at grakn.benchmark.profiler.GraknBenchmark.main(GraknBenchmark.java:57)
```

**Comment by flyingsilverfin** [comment]
Closed, no longer in use since reverting to cassandra thrift, #5370
