### ISSUE TITLE
Atom conversion error when using complex type for relation

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#5596]
## Description

We encounter this scenario: 
For a relation `A`, where `A` has a subtype `B`, and there is a rule to infer that `A` instances can be cast to `B` as a complex type.

In this case, any query for the `A` or `B` relations fails with an error, even without and data instances present.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load this schema:
```
define

currency sub attribute,
    datatype string,
    plays currency-adoption_currency-adopted;

end-date sub attribute,
    datatype string;

currency-adoption sub relation,
    has end-date,
    relates currency-adoption_adopting-country,
    relates currency-adoption_currency-adopted;

current-currency sub currency-adoption,
    relates currency-adoption_adopting-country,
    relates currency-adoption_currency-adopted;

country-currently-uses-currency sub rule,
when {
    $ca isa currency-adoption;
    not {$ca has end-date $ed;};
}, then {
    $ca isa current-currency;
};
```
2. Run this query
```
match $x isa currency; $c($x); get;
```
3. Receive the error:
```
Error: UNKNOWN: Attempted illegal atom conversion of atom [current-currency($ca)] to type [class grakn.core.graql.reasoner.atom.binary.RelationAtom].. Please check server logs for the stack trace.
All uncommitted data is cleared
```

4. We even get the same error when querying for the non-complex type:
```
match $x isa currency; $c($x) isa currency-adoption; get;
```

## Expected Output

There should be no results as no data has been inserted. I don't see any integrity issue with adding this complex type, so I presume this behaviour is unexpected and a bug.

## Stack trace
```
2020-02-26 15:14:14,398 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
grakn.core.kb.graql.reasoner.ReasonerException: Attempted illegal atom conversion of atom [current-currency($ca)] to type [class grakn.core.graql.reasoner.atom.binary.RelationAtom].
	at grakn.core.kb.graql.reasoner.ReasonerException.illegalAtomConversion(ReasonerException.java:71)
	at grakn.core.graql.reasoner.atom.Atom.toRelationAtom(Atom.java:91)
	at grakn.core.graql.reasoner.atom.binary.RelationAtom.isRuleApplicableViaAtom(RelationAtom.java:650)
	at grakn.core.graql.reasoner.atom.Atom.isRuleApplicable(Atom.java:233)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at grakn.core.graql.reasoner.atom.Atom.getApplicableRules(Atom.java:260)
	at grakn.core.graql.reasoner.atom.Atom.isRuleResolvable(Atom.java:142)
	at grakn.core.graql.reasoner.plan.ResolutionQueryPlan.queryPlan(ResolutionQueryPlan.java:78)
	at grakn.core.graql.reasoner.plan.ResolutionQueryPlan.<init>(ResolutionQueryPlan.java:52)
	at grakn.core.graql.reasoner.query.ReasonerQueryImpl.innerStateIterator(ReasonerQueryImpl.java:657)
	at grakn.core.graql.reasoner.state.ConjunctiveState.generateChildStateIterator(ConjunctiveState.java:48)
	at grakn.core.graql.reasoner.state.AnswerPropagatorState.<init>(AnswerPropagatorState.java:58)
	at grakn.core.graql.reasoner.state.ConjunctiveState.<init>(ConjunctiveState.java:40)
	at grakn.core.graql.reasoner.query.ReasonerQueryImpl.resolutionState(ReasonerQueryImpl.java:607)
	at grakn.core.graql.reasoner.state.RuleState.generateChildStateIterator(RuleState.java:52)
	at grakn.core.graql.reasoner.state.AnswerPropagatorState.<init>(AnswerPropagatorState.java:58)
	at grakn.core.graql.reasoner.state.RuleState.<init>(RuleState.java:45)
	at grakn.core.graql.reasoner.rule.InferenceRule.subGoal(InferenceRule.java:387)
	at grakn.core.graql.reasoner.query.ReasonerAtomicQuery.lambda$ruleStateIterator$9(ReasonerAtomicQuery.java:286)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1385)
	at grakn.core.graql.reasoner.state.AnswerPropagatorState.generateChildState(AnswerPropagatorState.java:63)
	at grakn.core.graql.reasoner.ResolutionIterator.findNextAnswer(ResolutionIterator.java:76)
	at grakn.core.graql.reasoner.ResolutionIterator.hasNext(ResolutionIterator.java:112)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at grakn.core.graql.executor.util.LazyMergingStream$1.hasNext(LazyMergingStream.java:56)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at grakn.core.server.rpc.SessionService$Iterators.next(SessionService.java:469)
	at grakn.core.server.rpc.SessionService$TransactionListener.next(SessionService.java:437)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:232)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by flyingsilverfin** [comment]
@jmsfltchr  in the investigation of this bug, we decided to disallow exactly what you have written but allow a slight modification:
```
when {
    $ca isa currency-adoption;
    not {$ca has end-date $ed;};
}, then {
    $ca isa current-currency;
};
```

modifying type of the relation is ambiguous, you need to specify how the roles will be re-mapped as well:
```
when {
    $ca (role-1: $x, role-2: $y) isa currency-adoption;
    not {$ca has end-date $ed;};
}, then {
    $ca (other-role-1: $x, other-role-2: $y) isa current-currency;
};
```
