### ISSUE TITLE
"java.lang.NullPointerException" when initializing a schema

### ISSUE THREAD

**Issue by fr33tux** [graknlabs/grakn#5680]
Hello,

## Description

This issue is related to https://github.com/OpenCTI-Platform/opencti/issues/594 from the OpenCTI project, version 3.1.0.
When starting OpenCTI and trying to initialize the schema Grakn fails with a `java.lang.NullPointerException` (see the full stacktrace below).

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): Grakn core 1.6.2
3. Grakn client: client-nodejs
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Install OpenCTI 3.0.3
2. Update to OpenCTI 3.1.0
3. OpenCTI passes successfully the 4 PRE-CHECK steps but fails at the GRAKN one with the stacktrace below.

## Expected Output

The Grakn schema is initialized successfully.

## Actual Output

```
2020-04-03 11:34:54,003 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: null
        at grakn.core.concept.impl.TypeImpl.lambda$checkNonOverlapOfImplicitRelations$16(TypeImpl.java:429)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
        at grakn.core.concept.impl.TypeImpl.checkNonOverlapOfImplicitRelations(TypeImpl.java:429)
        at grakn.core.concept.impl.TypeImpl.checkLinkAttributeIsLegal(TypeImpl.java:411)
        at grakn.core.concept.impl.TypeImpl.key(TypeImpl.java:404)
        at grakn.core.graql.executor.property.HasAttributeTypeExecutor$DefineHasAttributeType.execute(HasAttributeTypeExecutor.java:177)
        at grakn.core.graql.executor.WriteExecutorImpl.write(WriteExecutorImpl.java:240)
        at grakn.core.graql.executor.WriteExecutorImpl.write(WriteExecutorImpl.java:229)
        at grakn.core.graql.executor.QueryExecutorImpl.define(QueryExecutorImpl.java:364)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:383)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:632)
        at grakn.core.server.rpc.SessionService$TransactionListener.query(SessionService.java:345)
        at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:229)
        at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
 
## Additional information

/

**Comment by fr33tux** [comment]
This issue got fixed with by cleaning up some data, see the details there: https://github.com/OpenCTI-Platform/opencti/issues/594#issuecomment-617329491
