### ISSUE TITLE
clustering causes java.io.IOException: Mkdirs failed to create

### ISSUE THREAD

**Issue by snowparrot** [graknlabs/grakn#5863]
## Description

After loading a scheme and lots of data I type following query:
`compute cluster in [noun_clause], using connected-component;`
or` compute centrality using degree;`

I get the following message:
```

status = StatusCode.UNKNOWN
	details = "java.io.IOException: Mkdirs failed to create output/852791409/grakn.core.graql.analytics.DegreeDistributionMapReduce/_temporary/0/_temporary/attempt_20200730151034_0011_r_000003_0 (exists=false, cwd=file:/opt/grakn/core). Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1596114635.043395935","description":"Error received from peer ipv6:[::1]:48555","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"java.io.IOException: Mkdirs failed to create output/852791409/grakn.core.graql.analytics.DegreeDistributionMapReduce/_temporary/0/_temporary/attempt_20200730151034_0011_r_000003_0 (exists=false, cwd=file:/opt/grakn/core). Please check server logs for the stack trace.","grpc_status":2}"

```
## Environment
1. OS (where Grakn server runs): Fedora 32 
2. Grakn version (and platform):  Grakn Core 1.8, 
3. Grakn client: client-python,  console 
4. Other environment details:

## Reproducible Steps

1. Load the scheme 

```
define

text sub attribute,
    value string;

similarity sub attribute,
    value double;

noun_clause sub entity,
    key text,
    plays subject;

object_clause sub entity,
    has text,
    plays object;

sentence sub relation,
    relates subject,
    relates object;


similar_distance sub relation,
    has similarity,
    relates object,
    relates object;


similar_clustering sub relation,
    has similarity,
    relates object,
    relates object;

```

2. Loading lots of data
3.  Query `compute cluster in [noun_clause], using connected-component;`
or` compute centrality using degree;`
4. Output following

```
tatus = StatusCode.UNKNOWN
	details = "java.io.IOException: Mkdirs failed to create output/852791409/grakn.core.graql.analytics.DegreeDistributionMapReduce/_temporary/0/_temporary/attempt_20200730151034_0011_r_000003_0 (exists=false, cwd=file:/opt/grakn/core). Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1596114635.043395935","description":"Error received from peer ipv6:[::1]:48555","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"java.io.IOException: Mkdirs failed to create output/852791409/grakn.core.graql.analytics.DegreeDistributionMapReduce/_temporary/0/_temporary/attempt_20200730151034_0011_r_000003_0 (exists=false, cwd=file:/opt/grakn/core). Please check server logs for the stack trace.","grpc_status":2}"
```

and from the logs

```
2020-07-30 16:16:06,905 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.RuntimeException: java.io.IOException: Mkdirs failed to create output/1535810395/grakn.core.graql.analytics.ClusterMemberMapReduce/_temporary/0/_temporary/attempt_20200730161606_0041_r_000003_0 (exists=false, cwd=file:/opt/grakn/core)
	at grakn.core.graql.executor.OLAPOperation.asRuntimeException(OLAPOperation.java:107)
	at grakn.core.graql.executor.OLAPOperation.compute(OLAPOperation.java:77)
	at grakn.core.graql.executor.OLAPOperation.compute(OLAPOperation.java:87)
	at grakn.core.graql.executor.ComputeExecutorImpl.compute(ComputeExecutorImpl.java:170)
	at grakn.core.graql.executor.ComputeExecutorImpl.runComputeConnectedComponent(ComputeExecutorImpl.java:561)
	at grakn.core.graql.executor.ComputeExecutorImpl.runComputeCluster(ComputeExecutorImpl.java:528)
	at grakn.core.graql.executor.ComputeExecutorImpl.stream(ComputeExecutorImpl.java:153)
	at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:656)
	at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:722)
	at grakn.core.server.rpc.SessionService$TransactionListener.query(SessionService.java:398)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleIterRequest(SessionService.java:285)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:240)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:197)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Mkdirs failed to create output/1535810395/grakn.core.graql.analytics.ClusterMemberMapReduce/_temporary/0/_temporary/attempt_20200730161606_0041_r_000003_0 (exists=false, cwd=file:/opt/grakn/core)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:450)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:435)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:909)
	at org.apache.hadoop.io.SequenceFile$Writer.<init>(SequenceFile.java:1135)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:273)
	at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:530)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getSequenceWriter(SequenceFileOutputFormat.java:64)
	at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.getRecordWriter(SequenceFileOutputFormat.java:75)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$.org$apache$spark$internal$io$SparkHadoopMapReduceWriter$$executeTask(SparkHadoopMapReduceWriter.scala:137)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:89)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:88)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	... 3 common frames omitted
```

## Expected Output

Some clusters actually

## Actual Output

---
 
## Additional information

----

**Comment by snowparrot** [comment]
chmod 777 solves it
