### ISSUE TITLE
Server failing to start

### ISSUE THREAD

**Issue by zBalanovic** [graknlabs/grakn#5894]
## Description

{ 
Starting Storage....FAILED!
Unable to start Storage.
Process exited with code '3': 'java.lang.UnsatisfiedLinkError: ...

An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '3': 'java.lang.UnsatisfiedLinkError: C:\Users\e6540\AppData\Local\Temp\jna-94936928\jna2932615320693154299.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at org.apache.cassandra.utils.WindowsTimer.<clinit>(WindowsTimer.java:35)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:599)
        at grakn.core.server.GraknStorage.main(GraknStorage.java:38)
}

## Environment

1. OS (where Grakn server runs): {Windows 10 Pro}
2. Grakn version (and platform): { e.g. Grakn Core 1.8.3}
3. Grakn client: { }
4. Other environment details: {Java version 1.8.0_261}

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. {}
2. {}
3. {}
4. {}

## Expected Output

{ |To start server }

## Actual Output

{ I ran: grakn server start and it failed starting }
 
## Additional information

{  }

**Comment by haikalpribadi** [comment]
Hi @zBalanovic, sorry for the late response on this issue! Was busy working on 2.0 release at the end of last year. I know this issue no longer exists in Grakn 2.0.0-alpha. Have you got a chance to upgrade to latest Grakn? Unfortunately we won't be able to fix any issues in Grakn 1.8.X (and earlier) anymore at this point. So I will have to close this issue. Let me know if you have any challenges in upgrading to Grakn 2.0.0!
