### ISSUE TITLE
Facing error while querying data from grakn

### ISSUE THREAD

**Issue by GBkiriti** [graknlabs/grakn#5900]
## Description

I am trying to integrate dialogflow chatbot with nodejs webhook and grakn as graph database.
Whenever I try to query data from the grakn keyspace, I am facing the following error.
Error : 
TypeError: Cannot read property 'getImplicit' of undefined
    at new SchemaConcept (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/LocalConcept.js:83:56)
    at new Type (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/LocalConcept.js:102:1)
    at new AttributeType (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/LocalConcept.js:116:1)
    at Function.ConceptFactory.createLocalConcept (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/ConceptFactory.js:69:42)
    at new Thing (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/LocalConcept.js:95:37)
    at new Attribute (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/LocalConcept.js:107:9)
    at Function.ConceptFactory.createLocalConcept (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/concept/ConceptFactory.js:66:37)
    at /Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/util/AnswerFactory.js:54:43
    at jspb.Map.forEach (/Users/xxxx/yyyy/zzzz/node_modules/google-protobuf/google-protobuf.js:410:128)
    at AnswerFactory.createConceptmap (/Users/xxxx/yyyy/zzzz/node_modules/grakn-client/src/service/Session/util/AnswerFactory.js:53:24)

## Environment

1. OS (where Grakn server runs): { Mac OS 10 }
2. Grakn version : {  Grakn Core 1.8.4 }
3. Grakn client: {  client-nodejs}

**Comment by haikalpribadi** [comment]
Hi @GBkiriti, sorry for the late response on this issue! Was busy working on 2.0 release at the end of last year. I know this issue no longer exists in Grakn 2.0.0-alpha. Have you got a chance to upgrade to latest Grakn? Unfortunately we won't be able to fix any issues in Grakn 1.8.X (and earlier) anymore at this point. So I will have to close this issue. Let me know if you have any challenges in upgrading to Grakn 2.0.0!
