### ISSUE TITLE
Unable to save abstract entity schema twice

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#5941]
## Description

The following schema fails to save twice.

```gql
define
person sub entity,
    owns first-name;

name sub attribute, abstract, value string;
first-name sub name, value string;
```

It saves the first time but trying to save it again results in:
```
[TYW12] Invalid Type Write: The attribute type 'name' cannot be set to abstract as its subtypes are not abstract.
grakn.core.common.exception.GraknException: [TYW12] Invalid Type Write: The attribute type 'name' cannot be set to abstract as its subtypes are not abstract.
	at grakn.core.common.exception.GraknException.of(GraknException.java:51)
	at grakn.core.concept.type.impl.AttributeTypeImpl.setAbstract(AttributeTypeImpl.java:105)
	at grakn.core.query.Definer.defineAbstract(Definer.java:201)
	at grakn.core.query.Definer.define(Definer.java:123)
	at grakn.core.query.Definer.defineSub(Definer.java:178)
	at grakn.core.query.Definer.define(Definer.java:108)
	at grakn.core.query.Definer.lambda$defineOwns$2(Definer.java:230)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at grakn.core.query.Definer.defineOwns(Definer.java:229)
	at grakn.core.query.Definer.define(Definer.java:127)
	at grakn.core.query.Definer.lambda$execute$0(Definer.java:88)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at grakn.core.query.Definer.execute(Definer.java:87)
	at grakn.core.query.QueryManager.define(QueryManager.java:117)
	at grakn.core.server.rpc.query.QueryHandler.define(QueryHandler.java:110)
	at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:59)
	at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
	at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Environment

1. OS (where Grakn server runs): Ubuntu 20
2. Grakn version (and platform): Grakn Core 2.0.0-alpha (1e448d82af4d3f5caab12b1aceda7ea96657935f)
3. Grakn client: client-java

## Reproducible Steps

Save the above schema twice. I'm using the code:
```groovy
def graknHost = "localhost"
def graknPort = 1729
def graknKeyspace = "test100"
def graknClient = new GraknClient(graknHost + ":" + graknPort)
def schemaSession = graknClient.session(graknKeyspace, Grakn.Session.Type.SCHEMA)
def schemaFile = "../resources/simpledb.gql"

//save schema
def tx = schemaSession.transaction(Grakn.Transaction.Type.WRITE)
tx.query().define(
        Graql.parseQuery(new File(schemaFile).text) as GraqlDefine
)
tx.commit()
tx.close()

//save schema again
tx = schemaSession.transaction(Grakn.Transaction.Type.WRITE)
tx.query().define(
        Graql.parseQuery(new File(schemaFile).text) as GraqlDefine
)
tx.commit()
tx.close()

schemaSession.close()
graknClient.close()
```

With dependencies:
```
compile fileTree(dir: '/opt/grakn/grakn-core-all-linux-2.0.0/console/services/lib', include: ['*.jar'])
```

## Expected Output

Should result in no operation

## Actual Output

Fails to realize it's already saved the schema as defined
 
## Additional information

The first time I ran Grakn it threw an error:
```
$ ./grakn server
14:25:52,029 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:25:52,029 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:25:52,030 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/grakn/grakn-core-all-linux-2.0.0/server/conf/logback.xml]
14:25:52,030 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
14:25:52,030 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/grakn/grakn-core-all-linux-2.0.0/server/lib/common/io-grakn-core-grakn-server-bin-0.0.0.jar!/logback.xml]
14:25:52,030 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/grakn/grakn-core-all-linux-2.0.0/server/conf/logback.xml]
14:25:52,094 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:25:52,098 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/opt/grakn/grakn-core-all-linux-2.0.0/server/conf/logback.xml] 
14:25:52,098 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
14:25:52,101 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:25:52,103 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:25:52,106 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:25:52,118 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:25:52,120 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [LOGFILE]
14:25:52,121 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:25:52,141 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1884122755 - setting totalSizeCap to 1 GB
14:25:52,142 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1884122755 - Archive files will be limited to [50 MB] each.
14:25:52,143 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1884122755 - Will use gz compression
14:25:52,144 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1884122755 - Will use the pattern grakn.log-%d{yyyy-MM}.%i.log for the active file
14:25:52,146 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@43a0cee9 - The date pattern is 'yyyy-MM' from file name pattern 'grakn.log-%d{yyyy-MM}.%i.log.gz'.
14:25:52,146 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@43a0cee9 - Rollover at start of every month.
14:25:52,148 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@43a0cee9 - Setting initial period to Fri Dec 11 14:25:52 EST 2020
14:25:52,151 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOGFILE] - Active log file name: /opt/grakn/grakn-core-all-linux-2.0.0/server/logs//grakn.log
14:25:52,151 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOGFILE] - File property is set to [/opt/grakn/grakn-core-all-linux-2.0.0/server/logs//grakn.log]
14:25:52,151 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
14:25:52,152 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [grakn.core] to INFO
14:25:52,152 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [LOGFILE] to Logger[grakn.core]
14:25:52,152 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[grakn.core]
14:25:52,152 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:25:52,152 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@eb21112 - Registering current configuration as safe fallback point


====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |        |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
Exception in thread "grakn-elg::6" java.lang.NullPointerException
	at grakn.common.concurrent.actor.EventLoop.loop(EventLoop.java:87)
	at java.base/java.lang.Thread.run(Thread.java:834)
Grakn Core version: 2.0.0-alpha
Grakn Core Server has been started (in 503.010 ms)
^C
Shutting down Grakn Core Server...
Grakn Core Server has been shutdown
```

**Comment by BFergerson** [comment]
Fixed as of https://github.com/graknlabs/grakn/releases/tag/2.0.0-alpha
