### ISSUE TITLE
Unable to delete relationship records of type due to index overlap

### ISSUE THREAD

**Issue by suciokhan** [graknlabs/grakn#5980]
## Description

Attempting to remove relationship entities of type "employment" results in failure, with an index overlap error message.

## Environment

1. OS (where Grakn server runs): Ubuntu 20.04
2. Grakn version (and platform): Grakn Core 1.8.3
3. Grakn client: Using console directly for deleting, but used Python client for insert statements.
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Using Python client, insert about 500k employment relationships where start_date/stop_date look like YYYY-MM-DD. Then try to insert one where the date is 03-07-01-01 and break the batch insert.
2. Modify the Python code that does the inserts to handle goofed dates.
3. Go into the console to delete the entities of this type to try inserting again with the improved code
4. ./grakn console --keyspace xyz
5. get $e isa employment; delete $e isa employment;.

## Expected Output

I expected this to delete all my employment relationships so I can start doing an ingest again without having to worry about duplicate entries.

## Actual Output

`Error: UNKNOWN: grakn.core.kb.server.exception.TemporaryWriteException: Index overlap has led to the accidental sharing of a partially complete vertex {v[8384]}. Please check server logs for the stack trace.
All uncommitted data is cleared`

## Additional information

Here's the full log entry for this error:

`Error: UNKNOWN: grakn.core.kb.server.exception.TemporaryWriteException: Index overlap has led to the accidental sharing of a partially complete vertex {v[8384]}. Please check server logs for the stack trace.
All uncommitted data is cleared`

Stack trace for this error is as follows:

2020-12-25 14:51:24,178 [grpc-request-handler-5] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
java.util.concurrent.ExecutionException: grakn.core.kb.server.exception.TemporaryWriteException: Index overlap has led to the accidental sharing of a partially complete vertex {v[8384]}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at grakn.core.server.rpc.SessionService$TransactionListener.process(SessionService.java:319)
        at grakn.core.server.rpc.SessionService$TransactionListener.onNext(SessionService.java:196)
        at grakn.core.server.rpc.SessionService$TransactionListener.onNext(SessionService.java:156)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:779)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: grakn.core.kb.server.exception.TemporaryWriteException: Index overlap has led to the accidental sharing of a partially complete vertex {v[8384]}
        at grakn.core.kb.server.exception.TemporaryWriteException.indexOverlap(TemporaryWriteException.java:51)
        at grakn.core.concept.manager.ConceptManagerImpl.buildConcept(ConceptManagerImpl.java:551)
        at grakn.core.concept.manager.ConceptManagerImpl.buildConcept(ConceptManagerImpl.java:538)
        at grakn.core.graql.executor.TraversalExecutorImpl.createAnswer(TraversalExecutorImpl.java:85)
        at grakn.core.graql.executor.TraversalExecutorImpl.lambda$traverse$0(TraversalExecutorImpl.java:66)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal.forEachRemaining(Traversal.java:265)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at grakn.core.graql.executor.QueryExecutorImpl.delete(QueryExecutorImpl.java:228)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:514)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:700)
        at grakn.core.server.rpc.SessionService$TransactionListener.query(SessionService.java:388)
        at grakn.core.server.rpc.SessionService$TransactionListener.handleIterRequest(SessionService.java:278)
        at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:237)
        at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:196)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
Caused by: java.lang.IllegalStateException: Could not determine the base type of vertex [Vertex [8384] /n]
        at grakn.core.concept.manager.ConceptManagerImpl.getBaseType(ConceptManagerImpl.java:614)
        at grakn.core.concept.manager.ConceptManagerImpl.buildConcept(ConceptManagerImpl.java:549)
        ... 23 common frames omitted

**Comment by haikalpribadi** [comment]
Hi @suciokhan, sorry for the late response on this issue! Was busy working on 2.0 release at the end of last year. I know this issue no longer exists in Grakn 2.0.0-alpha. Have you got a chance to upgrade to latest Grakn? Unfortunately we won't be able to fix any issues in Grakn 1.8.X (and earlier) anymore at this point. So I will have to close this issue. Let me know if you have any challenges in upgrading to Grakn 2.0.0!
