### ISSUE TITLE
NullPointerException when performing match followed by match limit query

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/grakn#6011]
1. Use this distro: https://www.dropbox.com/s/1y3ophwlv6xyg2z/grakn-2.0-alpha-tomas-20210109.zip?dl=0
2. Enter the console with `./grakn console` and `transaction biograkn_covid_16 data read` 
3. Run `match $p isa protein;` (this should work)
4. Run `match $p isa protein; limit 1000; `
5. No results get returned and this error appears: 
```
java.lang.NullPointerException Please check server logs for the stack trace.
```
The Grakn logs show: 
```
grakn.core.common.exception.GraknException: java.lang.NullPointerException
	at grakn.core.common.exception.GraknException.of(GraknException.java:47)
	at grakn.core.common.producer.ProducerBuffer$Iterator.hasNext(ProducerBuffer.java:131)
	at grakn.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at grakn.core.common.iterator.DistinctIterator.fetchAndCheck(DistinctIterator.java:48)
	at grakn.core.common.iterator.DistinctIterator.hasNext(DistinctIterator.java:44)
	at grakn.core.common.iterator.LimitedIterator.hasNext(LimitedIterator.java:37)
	at grakn.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:43)
	at grakn.core.server.rpc.TransactionRPC$Iterators$BatchingIterator.iterateBatch(TransactionRPC.java:259)
	at grakn.core.server.rpc.TransactionRPC$Iterators.beginIteration(TransactionRPC.java:202)
	at grakn.core.server.rpc.TransactionRPC.respond(TransactionRPC.java:137)
	at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:95)
	at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
	at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
	at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException: null
	at grakn.core.concept.ConceptManager.lambda$conceptMap$0(ConceptManager.java:70)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1503)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1503)
	at grakn.core.traversal.common.VertexMap.forEach(VertexMap.java:57)
	at grakn.core.concept.ConceptManager.conceptMap(ConceptManager.java:68)
	at grakn.core.common.producer.MappedProducer$Sink.put(MappedProducer.java:53)
	at grakn.core.traversal.producer.VertexProducer.lambda$consume$0(VertexProducer.java:50)
	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
	at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
	at grakn.core.traversal.producer.VertexProducer.produce(VertexProducer.java:42)
	at grakn.core.common.producer.MappedProducer.produce(MappedProducer.java:35)
	at grakn.core.common.producer.ProducerBuffer.lambda$mayProduce$0(ProducerBuffer.java:73)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	... 5 common frames omitted
```

**Comment by tomassabat** [comment]
This seems to work now on the version that you gave me @lolski

**Comment by lolski** [comment]
Thank you! I'm closing the issue @tomassabat
