### ISSUE TITLE
NullPointerException from Match Query

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/grakn#6016]
## Description

Received a NullPointerException in the console when executing a match query.

## Environment

1. OS (where Grakn server runs): AWS
2. Grakn version (and platform): Grakn Core 2.0 alpha
3. Grakn client: console

## Reproducible Steps

Data is private and cannot be provided.

Opened a console and a read transaction, running this query:
```
<database>::data::read> match $g1 isa gene, has gene-id '1789'; $p1 isa protein;
> $gpe ($g1, $p1)isa gene-protein-encoding;
> $ppi ($p1, $p2) isa protein-protein-interaction;
> $gpe2 ($g2, $p2)isa gene-protein-encoding;
> $gndis ($g2, $d1) isa gene-disease-association;
> limit 5;
```

Here's the necessary schema:
```
gene-id sub attribute, value string;

gene sub entity, 
  owns gene-id @key,
  plays gene-disease-association:gene,
  plays gene-protein-encoding:gene;

disease sub entity,
  plays gene-disease-association:disease;

protein sub entity,
  plays gene-protein-encoding:protein,
  plays protein-protein-interaction:protein;

gene-protein-encoding sub relation,
  relates gene,
  relates protein;
  
protein-protein-interaction sub relation,
  relates protein;

gene-disease-association sub relation,
  relates gene,
  relates disease;
```

Some fabricated data:
```
insert 
$g1 isa gene, has gene-id '1789'; $p1 isa protein;
$g2 isa gene, has gene-id '1776'; $d1 isa disease; $p1 isa protein; $p2 isa protein;
$gpe (gene: $g1, protein:$p1) isa gene-protein-encoding;
$ppi (protein: $p1, protein: $p2) isa protein-protein-interaction;
$gpe2 (gene: $g2, protein: $p2) isa gene-protein-encoding;
$gndis (gene: $g2, disease: $d1) isa gene-disease-association;
```
Run this query N times to make more data if that helps to reproduce this:
```
match 
$g1 isa gene, has gene-id '1789'; $p1 isa protein;
insert
$g2 isa gene; $d1 isa disease; $p1 isa protein; $p2 isa protein;
$gpe (gene: $g1, protein:$p1) isa gene-protein-encoding;
$ppi (protein: $p1, protein: $p2) isa protein-protein-interaction;
$gpe2 (gene: $g2, protein: $p2) isa gene-protein-encoding;
$gndis (gene: $g2, disease: $d1) isa gene-disease-association;
```

Note that I copy-pasted this query into the console, and it has added a `>` before each line. This is unexpected, but other queries seem to be running fine despite this. The server log shows the output below. Re-running the query there were no further exceptions thrown, the results returned as expected.

```
Parameters: Parameters: {
	values: {pair($_0, = <STRING>)=[string: 1789]}
}
GraphProcedure: Graph Procedure: {
	vertices:
		$_0 [thing] { hasIID: false, types: [], predicates: [= <STRING>] } (start)
		$_gene [type] { labels: [gene], abstract: false, value: [], regex: null } (end)
		$_gene-disease-association [type] { labels: [gene-disease-association], abstract: false, value: [], regex: null } (end)
		$_gene-id [type] { labels: [gene-id], abstract: false, value: [], regex: null } (end)
		$_gene-protein-encoding [type] { labels: [gene-protein-encoding], abstract: false, value: [], regex: null }
		$_protein [type] { labels: [protein], abstract: false, value: [], regex: null } (end)
		$_protein-protein-interaction [type] { labels: [protein-protein-interaction], abstract: false, value: [], regex: null } (end)
		$d1 [thing] { hasIID: false, types: [], predicates: [] } (end)
		$g1 [thing] { hasIID: false, types: [], predicates: [] }
		$g2 [thing] { hasIID: false, types: [], predicates: [] }
		$gndis [thing] { hasIID: false, types: [], predicates: [] }
		$gpe [thing] { hasIID: false, types: [], predicates: [] }
		$gpe2 [thing] { hasIID: false, types: [], predicates: [] }
		$p1 [thing] { hasIID: false, types: [], predicates: [] }
		$p2 [thing] { hasIID: false, types: [], predicates: [] } (end)
		$ppi [thing] { hasIID: false, types: [], predicates: [] }
	edges:
		1: ($_0 <--[HAS]--* $g1)
		2: ($g1 <--[ROLEPLAYER]--* $gpe) { roleTypes: [] }
		3: ($gpe *--[ISA]--> $_gene-protein-encoding) { isTransitive: true }
		4: ($_gene-protein-encoding <--[ISA]--* $gpe2) { isTransitive: true }
		5: ($gpe2 *--[ROLEPLAYER]--> $g2) { roleTypes: [] }
		6: ($g2 <--[ROLEPLAYER]--* $gndis) { roleTypes: [] }
		7: ($gndis *--[ROLEPLAYER]--> $d1) { roleTypes: [] }
		8: ($gpe *--[ROLEPLAYER]--> $p1) { roleTypes: [] }
		9: ($p1 <--[ROLEPLAYER]--* $ppi) { roleTypes: [] }
		10: ($gpe2 *--[ROLEPLAYER]--> $p2) { roleTypes: [] }
		11: ($ppi *--[ISA]--> $_protein-protein-interaction) { isTransitive: true }
		12: ($gndis *--[ISA]--> $_gene-disease-association) { isTransitive: true }
		13: ($g1 *--[ISA]--> $_gene) { isTransitive: true }
		14: ($ppi *--[ROLEPLAYER]--> $p2) { roleTypes: [] }
		15: ($p1 *--[ISA]--> $_protein) { isTransitive: true }
		16: ($_0 *--[ISA]--> $_gene-id) { isTransitive: true }
}
java.lang.NullPointerException
grakn.core.common.exception.GraknException: java.lang.NullPointerException
	at grakn.core.common.exception.GraknException.of(GraknException.java:47)
	at grakn.core.common.producer.ProducerQueue$Iterator.hasNext(ProducerQueue.java:131)
	at grakn.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at grakn.core.common.iterator.DistinctIterator.fetchAndCheck(DistinctIterator.java:48)
	at grakn.core.common.iterator.DistinctIterator.hasNext(DistinctIterator.java:44)
	at grakn.core.common.iterator.LimitedIterator.hasNext(LimitedIterator.java:37)
	at grakn.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:43)
	at grakn.core.server.rpc.TransactionRPC$Iterators$BatchingIterator.iterateBatch(TransactionRPC.java:234)
	at grakn.core.server.rpc.TransactionRPC$Iterators.beginIteration(TransactionRPC.java:202)
	at grakn.core.server.rpc.TransactionRPC.respond(TransactionRPC.java:137)
	at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:95)
	at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
	at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
	at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NullPointerException: null
	at grakn.core.common.iterator.Iterators.iterate(Iterators.java:50)
	at grakn.core.graph.adjacency.impl.ThingAdjacencyImpl.lambda$bufferedEdgeIterator$0(ThingAdjacencyImpl.java:97)
	at grakn.core.common.iterator.FlatMappedIterator.initialiseAndSetState(FlatMappedIterator.java:62)
	at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:44)
	at grakn.core.common.iterator.LinkedIterators.hasNext(LinkedIterators.java:41)
	at grakn.core.common.iterator.DistinctIterator.fetchAndCheck(DistinctIterator.java:48)
	at grakn.core.common.iterator.DistinctIterator.hasNext(DistinctIterator.java:44)
	at grakn.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at grakn.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at grakn.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at grakn.core.traversal.producer.GraphIterator.computeFirstBranch(GraphIterator.java:110)
	at grakn.core.traversal.producer.GraphIterator.computeFirst(GraphIterator.java:102)
	at grakn.core.traversal.producer.GraphIterator.computeFirstBranch(GraphIterator.java:114)
	at grakn.core.traversal.producer.GraphIterator.computeFirst(GraphIterator.java:102)
	at grakn.core.traversal.producer.GraphIterator.computeFirstBranch(GraphIterator.java:114)
	at grakn.core.traversal.producer.GraphIterator.computeFirst(GraphIterator.java:102)
	at grakn.core.traversal.producer.GraphIterator.computeFirstBranch(GraphIterator.java:114)
	at grakn.core.traversal.producer.GraphIterator.computeFirst(GraphIterator.java:102)
	at grakn.core.traversal.producer.GraphIterator.computeFirstBranch(GraphIterator.java:114)
	at grakn.core.traversal.producer.GraphIterator.computeFirst(GraphIterator.java:102)
	at grakn.core.traversal.producer.GraphIterator.hasNext(GraphIterator.java:83)
	at grakn.core.common.iterator.DistinctIterator.fetchAndCheck(DistinctIterator.java:48)
	at grakn.core.common.iterator.DistinctIterator.hasNext(DistinctIterator.java:44)
	at grakn.core.traversal.producer.GraphProducer.produceAsync(GraphProducer.java:88)
	at grakn.core.traversal.producer.GraphProducer.lambda$produce$0(GraphProducer.java:75)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	... 4 common frames omitted
```

**Comment by lriuui0x0** [comment]
This doesn't seem to be reproducible

**Comment by haikalpribadi** [comment]
The client dataset has fully loaded till the end now without this bug ever occurring again. Given how much Grakn has changed in the 22 days since this issue is posted, we believe this bug has been resolved along the way.
