### ISSUE TITLE
[SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'ForkJoinPool-1-worker-9'. java.lang.OutOfMemoryError: GC overhead limit excede

### ISSUE THREAD

**Issue by gunnarklee** [graknlabs/grakn#6023]
## Description

when running batches of inserts server fails with memory error. This has happened multiple times for me. 

## Environment

OS (where Grakn server runs): ubuntu 16..04
Grakn version (and platform): grakn core all 2.0.0 alpha (1/12/21)
Grakn client = client-python v2.0.04a
Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

this may break it if we use this with multithreading and batch size over 100 (maybe over 1)
apid.load_apid_noisi(conn, client, keyspace, multithread = False, batch_size=1)

## Expected Output

I expected my inserts to continue

## Actual Output

SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'ForkJoinPool-1-worker-9'.
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at grakn.core.common.collection.Bytes.join(Bytes.java:49)
        at grakn.core.graph.adjacency.impl.TypeAdjacencyImpl$Persisted.edgeIterator(TypeAdjacencyImpl.java:145)
        at grakn.core.graph.adjacency.impl.TypeAdjacencyImpl$Persisted.edge(TypeAdjacencyImpl.java:153)
        at grakn.core.concept.type.impl.ThingTypeImpl.declaredOwns(ThingTypeImpl.java:226)
        at grakn.core.concept.type.impl.ThingTypeImpl.getOwns(ThingTypeImpl.java:273)
        at grakn.core.concept.type.impl.ThingTypeImpl.getOwns(ThingTypeImpl.java:273)
        at grakn.core.concept.thing.impl.ThingImpl.setHas(ThingImpl.java:106)
        at grakn.core.concept.thing.impl.ThingImpl.setHas(ThingImpl.java:99)
        at grakn.core.query.Inserter.lambda$insertHas$3(Inserter.java:289)
        at grakn.core.query.Inserter$$Lambda$324/1689340656.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at grakn.core.query.Inserter.insertHas(Inserter.java:289)
        at grakn.core.query.Inserter.insert(Inserter.java:141)
        at grakn.core.query.Inserter$$Lambda$302/360380471.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
        at grakn.core.query.Inserter.execute(Inserter.java:105)
        at grakn.core.query.QueryManager.lambda$insert$0(QueryManager.java:158)
        at grakn.core.query.QueryManager$$Lambda$296/335587777.apply(Unknown Source)
        at grakn.core.common.iterator.MappedIterator.next(MappedIterator.java:40)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at grakn.core.common.iterator.ResourceIterator.toList(ResourceIterator.java:110)
        at grakn.core.query.QueryManager.insert(QueryManager.java:158)
        at grakn.core.server.rpc.query.QueryHandler.insert(QueryHandler.java:139)
        at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:80)
        at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
        at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
        at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
        at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
[SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'ForkJoinPool-1-worker-2'.
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1043)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4595)
        at grakn.core.rocks.RocksStorage.iterate(RocksStorage.java:174)
        at grakn.core.graph.adjacency.impl.TypeAdjacencyImpl$Persisted.edgeIterator(TypeAdjacencyImpl.java:146)
        at grakn.core.graph.adjacency.impl.TypeAdjacencyImpl$Persisted.edge(TypeAdjacencyImpl.java:153)
        at grakn.core.concept.type.impl.RelationTypeImpl.getRelates(RelationTypeImpl.java:157)
        at grakn.core.concept.type.impl.RelationTypeImpl.getRelates(RelationTypeImpl.java:164)
        at grakn.core.concept.thing.impl.RelationImpl.addPlayer(RelationImpl.java:71)
        at grakn.core.concept.thing.impl.RelationImpl.addPlayer(RelationImpl.java:65)
        at grakn.core.query.Inserter.lambda$insertRelation$2(Inserter.java:276)
        at grakn.core.query.Inserter$$Lambda$310/1403949039.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at grakn.core.query.Inserter.insertRelation(Inserter.java:260)
        at grakn.core.query.Inserter.insertIsa(Inserter.java:212)
        at grakn.core.query.Inserter.insert(Inserter.java:138)
        at grakn.core.query.Inserter$$Lambda$302/360380471.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.j

**Comment by lriuui0x0** [comment]
Succeeded with single thread, batch size 1.

**Comment by gunnarklee** [comment]
This fails on Grakn 2.00.a1 but is fixed on Grakn 2.00.a2

**Comment by lriuui0x0** [comment]
Done.
