### ISSUE TITLE
Exception when trying to enter into the console

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/grakn#6029]
(this bug only happened once)

I refer to this Grakn distribution: https://www.dropbox.com/s/1y3ophwlv6xyg2z/grakn-2.0-alpha-tomas-20210109.zip?dl=0

In this distro I have loaded biomedical data as part of biograkn_covid. This was successful. I also queried for data successfully two days ago. Today I started Grakn 2.0 again and went into the console. I queried for data a few times which was successful. 

Then I wanted to get into the console again using these commands: 
`./grakn console`
`transaction biograkn_covid_16 data read `
But then I got this warning: 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/tasabat/Documents/GraknDists/grakn-core-all-mac-2.0.0-alpha/console/services/lib/com-google-protobuf-protobuf-java-3-5-1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Despite that warning, I manage to get in the console. However when I run: 
```biograkn_covid_16::data::read> match $g isa protein; ```
I get this error: 
```
[CLI1] Illegal Client State: The transaction has been closed and no further operation is allowed.
```
Then I open a new tab and I do again: 
`./grakn console`
`transaction biograkn_covid_16 data read `
I then get this exception: 
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at grakn.protocol.GraknGrpc$GraknBlockingStub.sessionOpen(GraknGrpc.java:571)
	at grakn.client.rpc.RPCSession.<init>(RPCSession.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:51)
	at grakn.console.GraknConsole.runTransactionRepl(GraknConsole.java:130)
	at grakn.console.GraknConsole.runRepl(GraknConsole.java:118)
	at grakn.console.GraknConsole.run(GraknConsole.java:70)
	at grakn.console.GraknConsole.main(GraknConsole.java:231)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1729
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Afterwards I am back in the terminal, i.e. I'm not in the Grakn console anymore. 

The Grakn 2.0 process also reports this: 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001296581b6, pid=35534, tid=51971
#
# JRE version: Java(TM) SE Runtime Environment (11.0.1+13) (build 11.0.1+13-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.1+13-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [librocksdbjni12257175451475336287.jnilib+0xa1b6]  Java_org_rocksdb_RocksIterator_next0+0x6
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/tasabat/Documents/GraknDists/grakn-core-all-mac-2.0.0-alpha/hs_err_pid35534.log
Compiled method (nm)  494643 1358     n 0       org.rocksdb.RocksIterator::next0 (native)
 total in heap  [0x0000000119a2d110,0x0000000119a2d498] = 904
 relocation     [0x0000000119a2d288,0x0000000119a2d2b8] = 48
 main code      [0x0000000119a2d2c0,0x0000000119a2d490] = 464
 oops           [0x0000000119a2d490,0x0000000119a2d498] = 8
Compiled method (c1)  494644 2176       3       grakn.core.rocks.RocksIterator::fetchAndCheck (79 bytes)
 total in heap  [0x000000011280ba10,0x000000011280c808] = 3576
 relocation     [0x000000011280bb88,0x000000011280bc68] = 224
 main code      [0x000000011280bc80,0x000000011280c460] = 2016
 stub code      [0x000000011280c460,0x000000011280c568] = 264
 oops           [0x000000011280c568,0x000000011280c570] = 8
 metadata       [0x000000011280c570,0x000000011280c5a8] = 56
 scopes data    [0x000000011280c5a8,0x000000011280c690] = 232
 scopes pcs     [0x000000011280c690,0x000000011280c7d0] = 320
 dependencies   [0x000000011280c7d0,0x000000011280c7d8] = 8
 nul chk table  [0x000000011280c7d8,0x000000011280c808] = 48
[thread 80387 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
```

**Comment by lriuui0x0** [comment]
@haikalpribadi No we can't.

**Comment by haikalpribadi** [comment]
Do we think we've solved it, or do you think it's still hidden, @lriuui0x0 ?

**Comment by VladGan** [comment]
closing this since 20 days ago biograkn_covid behaved completely differently and didn't load at all. I didn't see that issue recently

**Comment by suciokhan** [comment]
I'm seeing similar error in alpha-12 doing a batch insert with Grami- I did a lot of transactions that worked, but now it's spitting lots of `Client Error: The transaction has been closed and no further operation is allowed`.
