### ISSUE TITLE
Insert query returns non-existent IID

### ISSUE THREAD

**Issue by BFergerson** [graknlabs/grakn#6087]
## Description

After inserting data and getting the entity's IID, querying the database with that IID returns a non-existent entity error.

## Environment

1. OS (where Grakn server runs): Ubuntu 20
2. Grakn version (and platform): Grakn core 2.0.0-alpha-3
3. Grakn client: client-java 2.0.0-alpha-6

## Reproducible Steps

```java
import grakn.client.Grakn;
import grakn.client.GraknClient;
import grakn.client.concept.answer.ConceptMap;

import java.util.List;
import java.util.stream.Collectors;

import static graql.lang.Graql.*;

public class IssueTest {
    public static void main(String[] args) {
        var graknHost = "localhost";
        var graknPort = 1729;
        var graknKeyspace = "grakn";
        try (var graknClient = GraknClient.core(graknHost + ":" + graknPort)) {
            if (graknClient.databases().contains(graknKeyspace)) graknClient.databases().delete(graknKeyspace);
            graknClient.databases().create(graknKeyspace);
            try (var schemaSession = graknClient.session(graknKeyspace, Grakn.Session.Type.SCHEMA)) {
                try (var tx = schemaSession.transaction(Grakn.Transaction.Type.WRITE)) {
                    tx.query().define(parseQuery(
                            "define user sub entity, owns username; username sub attribute, value string;"
                    ));
                    tx.commit();
                }
            }

            try (var dataSession = graknClient.session(graknKeyspace, Grakn.Session.Type.DATA)) {
                getUserByIID(createUser("bfergerson", dataSession), dataSession);
            }
        }
    }

    static String createUser(String username, Grakn.Session session) {
        try (var writeTx = session.transaction(Grakn.Transaction.Type.WRITE)) {
            List<ConceptMap> createUserAnswer = writeTx.query().insert(insert(
                    var("u").isa("user").has("username", username)
            )).collect(Collectors.toList());
            writeTx.commit();

            return createUserAnswer.get(0).get("u").asEntity().getIID();
        }
    }

    static String getUserByIID(String iid, Grakn.Session session) {
        try (var readTx = session.transaction(Grakn.Transaction.Type.READ)) {
            List<ConceptMap> getUserAnswer = readTx.query().match(match(
                    var("u").iid(iid)
            ).get("u")).collect(Collectors.toList());
            return getUserAnswer.get(0).get("u").asEntity().getIID();
        }
    }
}
```

## Actual Output

```
2021-01-26 00:07:59,801 [ForkJoinPool-1-worker-11] [ERROR] grakn.core.rocks.RocksStorage - [THR04] Invalid Thing Read: The thing with IID '0x966e80017fffffffffffffff' is not found.
grakn.core.common.exception.GraknException: [THR04] Invalid Thing Read: The thing with IID '0x966e80017fffffffffffffff' is not found.
at grakn.core.common.exception.GraknException.of(GraknException.java:55)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.registerIID(TypeResolver.java:198)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.lambda$register$5(TypeResolver.java:192)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.register(TypeResolver.java:192)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.register(TypeResolver.java:158)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.<init>(TypeResolver.java:145)
at grakn.core.logic.tool.TypeResolver.resolve(TypeResolver.java:91)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:93)
at grakn.core.reasoner.Reasoner.lambda$execute$1(Reasoner.java:81)
at grakn.core.common.iterator.FlatMappedIterator.initialiseAndSetState(FlatMappedIterator.java:62)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:44)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:137)
at grakn.core.reasoner.Reasoner.execute(Reasoner.java:81)
at grakn.core.query.Matcher.execute(Matcher.java:102)
at grakn.core.query.QueryManager.match(QueryManager.java:82)
at grakn.core.query.QueryManager.match(QueryManager.java:76)
at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:94)
at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-01-26 00:07:59,803 [ForkJoinPool-1-worker-11] [ERROR] g.core.server.rpc.TransactionStream - [THR04] Invalid Thing Read: The thing with IID '0x966e80017fffffffffffffff' is not found.
grakn.core.common.exception.GraknException: [THR04] Invalid Thing Read: The thing with IID '0x966e80017fffffffffffffff' is not found.
at grakn.core.common.exception.GraknException.of(GraknException.java:55)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.registerIID(TypeResolver.java:198)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.lambda$register$5(TypeResolver.java:192)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.register(TypeResolver.java:192)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.register(TypeResolver.java:158)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
at grakn.core.logic.tool.TypeResolver$TraversalBuilder.<init>(TypeResolver.java:145)
at grakn.core.logic.tool.TypeResolver.resolve(TypeResolver.java:91)
at grakn.core.reasoner.Reasoner.producers(Reasoner.java:93)
at grakn.core.reasoner.Reasoner.lambda$execute$1(Reasoner.java:81)
at grakn.core.common.iterator.FlatMappedIterator.initialiseAndSetState(FlatMappedIterator.java:62)
at grakn.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:44)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:137)
at grakn.core.reasoner.Reasoner.execute(Reasoner.java:81)
at grakn.core.query.Matcher.execute(Matcher.java:102)
at grakn.core.query.QueryManager.match(QueryManager.java:82)
at grakn.core.query.QueryManager.match(QueryManager.java:76)
at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:94)
at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:68)
at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:96)
at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:130)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by haikalpribadi** [comment]
If you save an IID before you commit the concept, that IID will not be a valid one to use outside of that transaction, i.e. post-commit, @BFergerson. Are you sure you queried for the IID after the concept has been committed?

**Comment by haikalpribadi** [comment]
From the answer above, I can tell that you're returning an IID from the list of concept maps you previously retrieved prior to committing: `List<ConceptMap> createUserAnswer`. This would definitely return IIDs that are not valid for use after you commit the data.

**Comment by haikalpribadi** [comment]
I'm not sure if you've read the release notes: https://github.com/graknlabs/graql/releases/tag/2.0.0-alpha

But I'd like to raise to your attention this section:

> **Note that we continue to discourage you in using Concept iid.**
> The purpose of an iid is as an "internal identifier" that the server uses under-the-hood to refer to concepts. This was prematurely exposed in the earlier versions of Grakn. Referring to Concept iid is officially dangerous now: the iid of a concept before and after being committed to the database are different. So if you hold onto an iid of a concept you've just written to the database before you commit it, and try to use it to query the concept after it has been committed, it will not be a valid iid. If you would like to refer to a thing uniquely, you must declare a @key attribute for that thing, as a "primary key" to uniquely refer to the concept.

**Comment by BFergerson** [comment]
@haikalpribadi, thanks for reminding me of the release notes. I have gone through them but forgot about that one.
