### ISSUE TITLE
Benchmark fails with org.rocksdb.RocksDBException: Busy

### ISSUE THREAD

**Issue by lolski** [graknlabs/grakn#6092]
## Description

The job `test-performance-small-grakn` on `@graknlabs_benchmark` fails with `org.rocksdb.RocksDBException: Busy`.

## Environment

1. OS (where Grakn server runs): Linux (Grabl CI)
2. Grakn version (and platform): Grakn Core https://github.com/graknlabs/grakn/commit/b59f91a90c5a22a08fc339259d5b62731611df3a
3. Grakn client: { e.g. client-java, client-python, client-nodejs, or console }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

The issue can be observed by re-run the following benchmark's [performance workflow](https://grabl.io/graknlabs/benchmark/6b46e2e8dc7f5ccb14562e71c9b13e40f2bb5fbb).

Alternatively, you can try to reproduce it on your local machine:

1. Start Grakn Server:
  - ` bazel build //:assemble-mac-zip && unzip bazel-bin/grakn-core-all-mac.zip && cd grakn-core-all-mac`
  - `./grakn server`
2. Start Benchmark:
  -
    ```
    bazel run --config=rbe //:benchmark-small -- \
      --database-uri localhost:1729 \
      --disable-tracing
      --config-file /absolute/path/to/config/config_test.yml
    ```

## Expected Output

Benchmarks runs successfully

## Actual Output

Benchmark fails with the following exception:

```
grakn.client.common.exception.GraknClientException: org.rocksdb.RocksDBException: Busy Please check server logs for the stack trace.

at grakn.client.common.exception.GraknClientException.of(GraknClientException.java:48)

at grakn.client.rpc.RPCTransaction$Response$Done$Error.read(RPCTransaction.java:323)

at grakn.client.rpc.RPCTransaction$ResponseCollector.take(RPCTransaction.java:247)

at grakn.client.rpc.QueryFuture.get(QueryFuture.java:59)

at grakn.client.rpc.RPCTransaction.execute(RPCTransaction.java:153)

at grakn.client.rpc.RPCTransaction.commit(RPCTransaction.java:122)

at grakn.benchmark.grakn.driver.GraknOperation.save(GraknOperation.java:56)

at grakn.benchmark.common.agent.write.AgeUpdateAgent$City.run(AgeUpdateAgent.java:51)

at grakn.benchmark.common.agent.write.AgeUpdateAgent$City.run(AgeUpdateAgent.java:41)

at grakn.benchmark.common.agent.base.Agent$Region.lambda$runWithReport$0(Agent.java:155)

at grakn.benchmark.common.utils.Trace.trace(Trace.java:37)

at grakn.benchmark.common.agent.base.Agent$Region.runWithReport(Agent.java:154)

at grakn.benchmark.common.agent.base.Agent.iterateRegionalAgent(Agent.java:102)

at grakn.benchmark.common.agent.base.Agent.lambda$iterate$0(Agent.java:88)
```

**Comment by VladGan** [comment]
fixed ith latest updates to benchmark and grakn
