### ISSUE TITLE
Long transaction cause rocksdb unable to check commit conflict

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/grakn#6102]
```
2021-01-27 10:31:04,048 [ForkJoinPool-1-worker-11] [ERROR] g.core.server.rpc.TransactionStream - org.rocksdb.RocksDBException: Transaction could not check for conflicts for operation at SequenceNumber 3544129 as the MemTable only contains changes newer than SequenceNumber 5539141.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
grakn.core.common.exception.GraknException: org.rocksdb.RocksDBException: Transaction could not check for conflicts for operation at SequenceNumber 3544129 as the MemTable only contains changes newer than SequenceNumber 5539141.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
        at grakn.core.common.exception.GraknException.of(GraknException.java:51)
        at grakn.core.rocks.RocksTransaction$Data.commit(RocksTransaction.java:318)
        at grakn.core.server.rpc.TransactionRPC.commit(TransactionRPC.java:142)
        at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:89)
        at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:118)
        at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
        at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.rocksdb.RocksDBException: Transaction could not check for conflicts for operation at SequenceNumber 3544129 as the MemTable only contains changes newer than SequenceNumber 5539141.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
        at org.rocksdb.Transaction.commit(Native Method)
        at org.rocksdb.Transaction.commit(Transaction.java:206)
        at grakn.core.rocks.RocksStorage$TransactionBounded.commit(RocksStorage.java:262)
        at grakn.core.rocks.RocksStorage$Data.commit(RocksStorage.java:316)
        at grakn.core.rocks.RocksTransaction$Data.commit(RocksTransaction.java:310)
        ... 17 common frames omitted
```

This is caused by a particular long transaction trying to commit while too many other transactions have already committed in between. This can be a legit issue, but at the same time we have a bug in server during data loading, some particular transaction may take 100 times of usual commit validation time, which is abnormal. The long transaction has the same transaction size as other transactions, and this happens very infrequently.

**Comment by haikalpribadi** [comment]
This issue is duplicated here: https://github.com/graknlabs/grakn/issues/6102
