### ISSUE TITLE
match $x isa thing, has thing $y throws error

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/grakn#6132]
```
2021-02-04 13:28:25,703 [grakn-core-main::4] [ERROR] grakn.core.rocks.RocksStorage - [QRY15] Invalid Query Pattern: The conjunction $y isa thing;
$x isa thing, has $y; can never be satisfied within the current schema.
grakn.core.common.exception.GraknException: [QRY15] Invalid Query Pattern: The conjunction $y isa thing;
$x isa thing, has $y; can never be satisfied within the current schema.
	at grakn.core.common.exception.GraknException.of(GraknException.java:55)
	at grakn.core.reasoner.Reasoner.producer(Reasoner.java:117)
	at grakn.core.reasoner.Reasoner.lambda$execute$2(Reasoner.java:98)
	at grakn.core.common.iterator.MappedIterator.next(MappedIterator.java:40)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:136)
	at grakn.core.reasoner.Reasoner.execute(Reasoner.java:98)
	at grakn.core.query.Matcher.execute(Matcher.java:122)
	at grakn.core.query.Matcher.execute(Matcher.java:118)
	at grakn.core.query.QueryManager.match(QueryManager.java:71)
	at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:104)
	at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:71)
	at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:101)
	at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:118)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-02-04 13:28:25,704 [grakn-core-main::4] [ERROR] g.core.server.rpc.TransactionStream - [QRY15] Invalid Query Pattern: The conjunction $y isa thing;
$x isa thing, has $y; can never be satisfied within the current schema.
grakn.core.common.exception.GraknException: [QRY15] Invalid Query Pattern: The conjunction $y isa thing;
$x isa thing, has $y; can never be satisfied within the current schema.
	at grakn.core.common.exception.GraknException.of(GraknException.java:55)
	at grakn.core.reasoner.Reasoner.producer(Reasoner.java:117)
	at grakn.core.reasoner.Reasoner.lambda$execute$2(Reasoner.java:98)
	at grakn.core.common.iterator.MappedIterator.next(MappedIterator.java:40)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at grakn.core.common.iterator.AbstractResourceIterator.toList(AbstractResourceIterator.java:136)
	at grakn.core.reasoner.Reasoner.execute(Reasoner.java:98)
	at grakn.core.query.Matcher.execute(Matcher.java:122)
	at grakn.core.query.Matcher.execute(Matcher.java:118)
	at grakn.core.query.QueryManager.match(QueryManager.java:71)
	at grakn.core.server.rpc.query.QueryHandler.match(QueryHandler.java:104)
	at grakn.core.server.rpc.query.QueryHandler.handleRequest(QueryHandler.java:71)
	at grakn.core.server.rpc.TransactionRPC.handleRequest(TransactionRPC.java:101)
	at grakn.core.server.rpc.TransactionStream.handleRequest(TransactionStream.java:118)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:82)
	at grakn.core.server.rpc.TransactionStream.onNext(TransactionStream.java:48)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by haikalpribadi** [comment]
Fixed by https://github.com/graknlabs/grakn/commit/f567bd4ad34c5a3e91a77d3b30cee3a4334479ec
