### ISSUE TITLE
Starting and Stopping via script eventually leads to failure

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/grakn#807]
General

This is a fun one. I was repeatedly running:

clear && ./grakn.sh clean && ./grakn.sh start

Whilst working on my side migration project. After running the above enough times I get this:

Filipes-MacBook-Pro:bin filipe$ clear && ./grakn.sh clean && ./grakn.sh start
Stopping engine
Stopping cassandra
Are you sure you want to delete all stored data and logs? [y/N] y
Deleted data in /Users/filipe/Databases/grakn-dist-0.9.0-SNAPSHOT/db
Deleted logs in /Users/filipe/Databases/grakn-dist-0.9.0-SNAPSHOT/logs
Starting cassandra
.objc[23645]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

Starting engine.ERROR 15:09:35 Error starting local jmx server:
java.rmi.server.ExportException: Port already in use: 7199; nested exception is:
 java.net.BindException: Address already in use
 at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:341)
 at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:249)
 at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
 at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
 at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:212)
 at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:152)
 at sun.rmi.registry.RegistryImpl.&lt;init&gt;(RegistryImpl.java:112)
 at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239)
 at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:96)
 at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:216)
 at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:537)
 at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:626)
Caused by: java.net.BindException: Address already in use
 at java.net.PlainSocketImpl.socketBind(Native Method)
 at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
 at java.net.ServerSocket.bind(ServerSocket.java:375)
 at java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:237)
 at javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
 at org.apache.cassandra.utils.RMIServerSocketFactoryImpl.createServerSocket(RMIServerSocketFactoryImpl.java:13)
 at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
 at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:330)
 ... 11 common frames omitted
2016-12-12 15:09:36.081:INFO::Thread-0: Logging initialized @661ms

Grakn LOG file located at [/Users/filipe/Databases/grakn-dist-0.9.0-SNAPSHOT/bin/../logs/grakn.log]

==================================================

 ___ ___ ___ _ __ _ _ ___ ___
 / __|| _ \/ \| |/ /| \| | / \|_ _|
 | (_ || /| - || ' &lt; | .` | _ | - | | |
 \___||_|_\|_|_||_|\_\|_|\_|(_)|_|_||___|

 Web Dashboard available at [http://0.0.0.0:4567]

==================================================
ERROR 15:09:36 Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: localhost/127.0.0.1:7000 is in use by another process. Change listen_address:storage_port in cassandra.yaml to values that do not conflict with other services
 at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:496)
 at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:442)
 at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:805)
 at org.apache.cassandra.service.StorageService.initServer(StorageService.java:720)
 at org.apache.cassandra.service.StorageService.initServer(StorageService.java:611)
 at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:378)
 at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:537)
 at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:626)
localhost/127.0.0.1:7000 is in use by another process. Change listen_address:storage_port in cassandra.yaml to values that do not conflict with other services
Fatal configuration error; unable to start server. See log for stacktrace.
ERROR 15:09:36 Exception in thread Thread[StorageServiceShutdownHook,5,main]
java.lang.NullPointerException: null
 at org.apache.cassandra.service.StorageService.getApplicationStateValue(StorageService.java:1591)
 at org.apache.cassandra.service.StorageService.getTokensFor(StorageService.java:1599)
 at org.apache.cassandra.service.StorageService.handleStateNormal(StorageService.java:1653)
 at org.apache.cassandra.service.StorageService.onChange(StorageService.java:1492)
 at org.apache.cassandra.gms.Gossiper.doOnChangeNotifications(Gossiper.java:1183)
 at org.apache.cassandra.gms.Gossiper.addLocalApplicationState(Gossiper.java:1412)
 at org.apache.cassandra.gms.Gossiper.stop(Gossiper.java:1438)
 at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:678)
 at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
 at java.lang.Thread.run(Thread.java:745)
.
Filipes-MacBook-Pro:bin filipe$ clear && ./grakn.sh clean && ./grakn.sh start

 

The above can be reproduced by simply running  clear && ./grakn.sh clean && ./grakn.sh start enough times

**Comment by kengcher** [comment]
Hi Haikal

I have the same problem and tried clean and start multiple times but it is still not working:

Stopping engine
/usr/local/Cellar/grakn/0.16.0/libexec/bin/grakn-engine.sh: line 88: kill: (81907) - No such process
Stopping cassandra
/usr/local/Cellar/grakn/0.16.0/libexec/bin/grakn-cassandra.sh: line 78: kill: (81847) - No such process
Are you sure you want to delete all stored data and logs? [y/N] y
Deleted data in /usr/local/Cellar/grakn/0.16.0/libexec/db
Deleted logs in /usr/local/Cellar/grakn/0.16.0/libexec/logs
Cleaning redis
OK
Starting redis
Starting cassandra 
.objc[82110]: Class JavaLaunchHelper is implemented in both /usr/bin/java and /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

Starting engine.
ksoh@WITSC02RX1EQFVH:~/$ EngineId.of(WITSC02RX1EQFVH-c90936af-081e-493e-871c-1de6953ebd1e) is initializing the system ontology
localhost/127.0.0.1:7000 is in use by another process.  Change listen_address:storage_port in cassandra.yaml to values that do not conflict with other services
Fatal configuration error; unable to start server.  See log for stacktrace.
